/**
 * PLACEHOLDER DATA — for building and previewing the UI before Supabase
 * is connected. Every query that reads this file today should be swapped
 * for a real Supabase query later (see /supabase/migrations for the
 * matching schema). Search the codebase for "mock-data" when wiring up
 * the database.
 */
import type { Agency, Package, BlogPost, Maulavi, Inquiry } from "@/types/domain";

// Locally generated placeholders (public/placeholders) — no external image
// service dependency during development. Swap for Supabase Storage URLs
// once real photos are uploaded.
const AGENCY_LOGOS: Record<string, string> = {
  "NM Travels": "/placeholders/logo-nm-travels.png",
  "Zaid Travels": "/placeholders/logo-zaid.png",
  "Akbar Travels": "/placeholders/logo-akbar.png",
  "SMS Travels": "/placeholders/logo-sms.png",
};
// `..._rest` soaks up the old (seed, bg) / (seed) call sites below without
// needing to touch every call — the values were only ever used to pick a
// deterministic-looking placeholder, which the lookup table / cycle already do.
const avatar = (seed: string, ..._rest: unknown[]) =>
  AGENCY_LOGOS[seed] ?? "/placeholders/logo-nm-travels.png";

// 9 visually distinct icons (gate, dome+minarets, Kaaba, crescent+star, flight
// path, tasbih beads, qibla compass, suitcase, passport+ticket) — one per
// current agency/package below, so no two cards show the identical cover.
const COVER_IMAGES = [
  "/placeholders/cover-1.jpg",
  "/placeholders/cover-2.jpg",
  "/placeholders/cover-3.jpg",
  "/placeholders/cover-4.jpg",
  "/placeholders/cover-5.jpg",
  "/placeholders/cover-6.jpg",
  "/placeholders/cover-7.jpg",
  "/placeholders/cover-8.jpg",
  "/placeholders/cover-9.jpg",
];
let coverIndex = 0;
const cover = (..._rest: unknown[]) => {
  const img = COVER_IMAGES[coverIndex % COVER_IMAGES.length];
  coverIndex += 1;
  return img;
};

// Blog posts get their own dedicated pool of covers (distinct line-art
// motifs — crescent & star, mosque dome, compass, lantern, etc. — instead
// of sharing the small agency/package cover pool above, which made
// adjacent blog cards look like duplicates of each other). Each post picks
// its cover explicitly rather than cycling, so the motif can loosely match
// the article's topic.
const BLOG_COVERS = {
  crescentStar: "/placeholders/blog-cover-1.jpg",
  mosque: "/placeholders/blog-cover-2.jpg",
  compass: "/placeholders/blog-cover-3.jpg",
  lantern: "/placeholders/blog-cover-4.jpg",
  suitcase: "/placeholders/blog-cover-5.jpg",
  calendar: "/placeholders/blog-cover-6.jpg",
  tasbih: "/placeholders/blog-cover-7.jpg",
  paperPlane: "/placeholders/blog-cover-8.jpg",
} as const;

// Real agencies, sourced from their own public Facebook/Meta ad creatives
// (screenshotted by the site owner 2026-09). No rating/badges/years are set
// unless the ad itself stated them — this platform never invents trust
// signals for a real business (see travelAgencySchema's note on
// aggregateRating). Logos are simple generated monograms (not the agency's
// actual brand logo) until real logo files are supplied.
export const mockAgencies: Agency[] = [
  {
    id: "a1",
    slug: "nm-travels-tours",
    name: "NM Travels & Tours PVT LTD",
    logoUrl: avatar("NM Travels"),
    coverImageUrl: cover("nm"),
    description:
      "Umrah & Hajj operator based in Wellawatte, Colombo. IATA member and Saudi Hajj Ministry-approved organization, running group Umrah departures with full-board Sri Lankan meals.",
    city: "Colombo",
    address: "#573, Habib Bank Building, Galle Road, Wellawatte, Colombo 06",
    phone: "+94 71 279 9648",
    whatsapp: "https://wa.me/94712799648",
    badges: [],
    packageCount: 2,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a2",
    slug: "zaid-travels-tours",
    name: "Zaid Travels & Tours (PVT) LTD",
    logoUrl: avatar("Zaid Travels"),
    coverImageUrl: cover("zaid"),
    description:
      "Umrah operator on Mosque Road, Beruwala, running a fixed premium 11-day departure with hotels close to Haram and Masjid Nabawi, and 3 Umrahs included.",
    city: "Beruwala",
    address: "Mosque Road, Beruwala",
    phone: "+94 76 738 4104",
    whatsapp: "https://wa.me/94767384104",
    badges: [],
    packageCount: 1,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a3",
    slug: "akbar-travels-and-tours",
    name: "Akbar Travels and Tours (PVT) LTD",
    logoUrl: avatar("Akbar Travels"),
    coverImageUrl: cover("akbar"),
    description:
      "IATA-accredited Umrah operator in Wellampitiya, Colombo, marking its 10th anniversary with September–November 2026 departures on Etihad Airways and SalamAir, staying at named Makkah and Madinah hotels.",
    city: "Colombo",
    address: "119/18, Megoda Kolonnawa Road, Wellampitiya",
    phone: "+94 76 694 5592",
    whatsapp: "https://wa.me/94716370349",
    badges: [],
    yearsActive: 10,
    packageCount: 3,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a4",
    slug: "sms-travels-tours",
    name: "SMS Travels & Tours (Pvt) Ltd",
    logoUrl: avatar("SMS Travels"),
    coverImageUrl: cover("sms"),
    description:
      "17+ year Umrah operator in Maradana, Colombo (CAA Sri Lanka & IATA approved), offering four package tiers — Normal to Platinum — across the same set of September 2026 departure dates.",
    city: "Colombo",
    address: "19/20 Abdullah Building, Symonds Road, Maradana, Colombo 10",
    phone: "+94 77 616 2323",
    whatsapp: "https://wa.me/94776162323",
    badges: [],
    yearsActive: 17,
    packageCount: 4,
    isActive: true,
    createdAt: "2026-09-03",
  },
];

// Real packages, transcribed from the same agency ad screenshots as
// mockAgencies above. Where an ad didn't state a specific fact (an airline,
// a named hotel, a star rating), that field says so honestly instead of
// guessing — see the optional makkahHotelStars/madinahHotelStars/email
// fields on the Agency/Package types. Engagement counts (view/click/etc.)
// start at 0 — these are brand-new real listings with no platform history
// yet, not carried-over demo traffic.
export const mockPackages: Package[] = [
  {
    id: "p1",
    slug: "nm-umrah-11-day-sept-20-early",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Early Group Departure (Sept 20)",
    coverImageUrl: cover("pkg1"),
    images: [cover("pkg1a")],
    priceLkr: 339000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-20"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p2",
    slug: "nm-umrah-11-day-sept-group",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Group Departure (Sept 12 & 26)",
    coverImageUrl: cover("pkg2"),
    images: [cover("pkg2a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-12", "2026-09-26"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p3",
    slug: "zaid-premium-11-day-oct-22",
    agencyId: "a2",
    agency: mockAgencies[1],
    title: "Premium 11-Day Umrah Package (22 Oct Departure)",
    coverImageUrl: cover("pkg3"),
    images: [cover("pkg3a")],
    priceLkr: 375000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Makkah hotel 500m from Haram (name TBA — confirm with agency)",
    madinahHotel: "Madinah hotel 300m from Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan meals",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "3 Umrahs included",
      "Ziyarah tours",
      "Sri Lankan meals",
      "Guide",
      "Free Jorana & Badr tour",
    ],
    exclusions: [],
    departureDates: ["2026-10-22"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p4",
    slug: "akbar-umrah-10-day-sept-16-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Sept 16 Departure (Etihad Airways)",
    coverImageUrl: cover("pkg4"),
    images: [cover("pkg4a")],
    priceLkr: 350000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p5",
    slug: "akbar-umrah-11-day-sept-16-salamair",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "11-Day Umrah — Sept 16 Departure (SalamAir)",
    coverImageUrl: cover("pkg5"),
    images: [cover("pkg5a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "SalamAir",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (SalamAir)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p6",
    slug: "akbar-umrah-10-day-oct-nov-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Oct 22 / Nov 19 Departures (Etihad Airways)",
    coverImageUrl: cover("pkg6"),
    images: [cover("pkg6a")],
    priceLkr: 360000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-10-22", "2026-11-19"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p7",
    slug: "sms-umrah-normal-10-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Normal Package — 10-Day Umrah",
    coverImageUrl: cover("pkg7"),
    images: [cover("pkg7a")],
    priceLkr: 349000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "economy",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p8",
    slug: "sms-umrah-silver-12-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Silver Package — 12-Day Umrah",
    coverImageUrl: cover("pkg8"),
    images: [cover("pkg8a")],
    priceLkr: 379000,
    durationDays: 12,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p9",
    slug: "sms-umrah-golden-15-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Golden Package — 15-Day Umrah",
    coverImageUrl: cover("pkg9"),
    images: [cover("pkg9a")],
    priceLkr: 399000,
    durationDays: 15,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p10",
    slug: "sms-umrah-platinum-18-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Platinum Package — 18-Day Umrah",
    coverImageUrl: cover("pkg10"),
    images: [cover("pkg10a")],
    priceLkr: 469000,
    durationDays: 18,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "first-time-umrah-checklist",
    title: "First-Time Umrah: The Complete Pre-Departure Checklist",
    excerpt:
      "Everything Sri Lankan pilgrims need to prepare — documents, packing, health requirements, and etiquette — before their first Umrah journey.",
    content: [
      "Performing Umrah for the first time is a deeply emotional milestone, and a little preparation goes a long way toward making the journey smooth and stress-free. This checklist covers the essentials every Sri Lankan pilgrim should sort out before departure.",
      "Documents first: make sure your passport has at least six months of validity remaining, and confirm your Umrah visa has been processed by your travel agency well ahead of departure. Keep printed and digital copies of your passport, visa, vaccination certificate, and flight tickets in a separate folder from the originals.",
      "Health requirements for Umrah typically include a Meningitis (ACYW135) vaccination certificate, valid for the period specified by Saudi health authorities, and seasonal requirements such as flu vaccination during certain periods. Check with your agency for the latest requirements, as these are updated periodically by the Saudi Ministry of Hajj and Umrah.",
      "Packing for Umrah is different from typical travel. Men should pack at least two sets of Ihram cloth (unstitched white garments) along with a money belt, and comfortable slip-on sandals for the many trips in and out of the mosque. Women should pack loose, modest clothing in breathable fabrics, and a comfortable pair of walking shoes — you will be on your feet far more than you expect.",
      "Finally, take time to learn the basic rites and duas of Umrah before you travel — Ihram, Tawaf, Sa'i, and Halq/Taqsir — so that you can focus on the spiritual experience rather than fumbling through the sequence on the day. Most reputable agencies provide a pre-departure briefing; attend it even if you've researched independently.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-07-20",
    status: "published",
  },
  {
    id: "b2",
    slug: "best-time-to-perform-umrah",
    title: "When Is the Best Time to Perform Umrah? A Season-by-Season Guide",
    excerpt:
      "Comparing crowd levels, weather, and pricing across Ramadan, Hajj season, and the rest of the year.",
    content: [
      "Umrah can be performed at any time of the year, but when you choose to go significantly affects crowd levels, weather, and the price of your package. Here's how the year generally breaks down for Sri Lankan pilgrims.",
      "Ramadan is the most spiritually rewarding time to perform Umrah, with the reward said to be equivalent to Hajj in virtue. It is also, unsurprisingly, the busiest and most expensive period — expect significantly higher package prices and larger crowds at the Haramain, especially in the last ten nights.",
      "The months immediately after Hajj (roughly Muharram through Safar) tend to be quieter and more affordable, as the post-Hajj rush has settled and Ramadan demand hasn't yet begun. This is often the best balance of comfortable crowd levels and reasonable pricing.",
      "Weather-wise, Makkah and Madinah are extremely hot from May through September, often exceeding 40°C. Pilgrims with health conditions, older family members, or young children may prefer the cooler months from November to February.",
      "If budget is the primary concern, avoid school holiday periods (which drive up demand from other countries) and Ramadan. Compare a few packages across different months on UmrahPackages.lk to see how much the timing itself moves the price.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-06-05",
    status: "published",
  },
  {
    id: "b3",
    slug: "umrah-dua-guide",
    title: "Essential Duas for Every Step of Umrah",
    excerpt: "A pilgrim's pocket guide to the key duas for Tawaf, Sa'i, and Ihram.",
    content: [
      "While there is no single obligatory dua for each step of Umrah — you may supplicate in your own words and language — there are well-known duas the Prophet ﷺ and his companions are reported to have recited, and learning them adds structure and meaning to each rite.",
      "Entering Ihram: recite the Talbiyah repeatedly from the moment you enter the state of Ihram until you begin Tawaf: 'Labbayk Allahumma labbayk, labbayka la sharika laka labbayk...' ('Here I am, O Allah, here I am. Here I am, You have no partner, here I am...').",
      "During Tawaf: there is no fixed dua for each circuit — pilgrims commonly recite the dua between the Yemeni Corner and the Black Stone: 'Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar' ('Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire').",
      "During Sa'i: while walking between Safa and Marwah, pilgrims often recite Qur'anic verses and personal supplications freely — this is an excellent time for heartfelt, personal dua in your own language.",
      "After Halq/Taqsir: once the hair is cut or trimmed and Umrah is complete, it is customary to thank Allah and make dua for acceptance of the pilgrimage. Our Islamic Tools page has a Dua of the Day feature if you'd like to continue building a habit of daily supplication after you return home.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Spiritual",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 10,
    publishedAt: "2026-05-18",
    status: "published",
  },
  {
    id: "b4",
    slug: "choosing-the-right-umrah-agency",
    title: "How to Choose the Right Umrah Travel Agency in Sri Lanka",
    excerpt:
      "What to check before you commit — licensing, reviews, itinerary transparency, and red flags to avoid.",
    content: [
      "With dozens of travel agencies in Sri Lanka offering Umrah packages, choosing the right one can feel overwhelming. Here's a practical checklist to work through before you commit.",
      "Verify licensing first. A legitimate Umrah operator should be registered and able to show proof of their travel agency license and any relevant IATA or SLTDA registration. Gold Verified and Premium Partner badges on UmrahPackages.lk are only issued after this kind of vetting.",
      "Read the itinerary line by line. A trustworthy agency will clearly state hotel names (not just star ratings), distance from the Haram, flight routing and layovers, and exactly what's included versus what costs extra (visa fees, Ziyarah tours, meals).",
      "Ask about the on-ground team. Reputable agencies have a dedicated coordinator or guide (often a Maulavi) accompanying or based in Makkah and Madinah who can assist with logistics and religious guidance during your stay.",
      "Be cautious of prices that are dramatically below the market average — this is often a sign of hidden costs, downgraded hotels after booking, or, in rare cases, outright scams. Compare a handful of packages side by side on our Compare page before making a decision, and always confirm final details directly with the agency over WhatsApp or phone.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-04-10",
    status: "published",
  },
  {
    id: "b5",
    slug: "umrah-packing-list-for-women",
    title: "The Complete Umrah Packing List for Women",
    excerpt: "Modest, comfortable, and practical — everything Sri Lankan women should pack for Umrah.",
    content: [
      "Packing for Umrah as a woman is about balancing modesty, comfort, and practicality for long days of walking and standing. Here is a complete list to work from.",
      "Clothing: pack loose-fitting, non-see-through abayas or modest outfits in breathable fabrics — cotton blends handle the heat far better than synthetic materials. Bring at least one dedicated white or light-colored outfit that meets Ihram conditions if your madhab/family custom calls for it, plus a few headscarves in easy-to-tie styles.",
      "Footwear: comfortable, well broken-in walking shoes are non-negotiable — you'll easily walk 15,000+ steps a day between the hotel, the Haram, and Sa'i. Pack a lightweight pair of sandals for inside the mosque.",
      "Toiletries: unscented soap and wudhu-friendly products (scented items are discouraged in the state of Ihram), a small first-aid kit, and any personal medication clearly labeled with your name.",
      "Extras worth packing: a small prayer mat or mat cover for airport/layover prayers, a portable charger, a lightweight shawl for air-conditioned mosque halls, and a few zip-lock bags for damp or dusty items on the way home.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-03-02",
    status: "published",
  },
  {
    id: "b6",
    slug: "umrah-vs-hajj-whats-the-difference",
    title: "Umrah vs. Hajj: What's the Difference?",
    excerpt: "A clear, simple breakdown of how Umrah and Hajj differ in timing, rites, and obligation.",
    content: [
      "Umrah and Hajj are both pilgrimages to Makkah, and they share several rites, but they differ in timing, obligation, and scale. Understanding the difference helps first-time pilgrims plan the right journey for their circumstances.",
      "Timing: Hajj can only be performed during a specific window in the Islamic calendar — the 8th to 13th of Dhu al-Hijjah. Umrah, on the other hand, can be performed at any time of the year, which is why it's often called the 'minor pilgrimage.'",
      "Obligation: Hajj is one of the Five Pillars of Islam and is obligatory once in a lifetime for every Muslim who is physically and financially able. Umrah is highly recommended (sunnah mu'akkadah in most views) but not obligatory in the same way.",
      "Rites: Hajj includes all the rites of Umrah (Ihram, Tawaf, Sa'i) plus additional rites unique to it — standing at Arafah, staying overnight at Muzdalifah and Mina, and the symbolic stoning of the Jamarat. Umrah is a shorter set of rites that can typically be completed within a few hours.",
      "Scale: Hajj draws several million pilgrims within the same short window each year, making logistics and crowd management far more complex than Umrah, which spreads pilgrims across the entire year.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 5,
    publishedAt: "2026-02-14",
    status: "published",
  },
  {
    id: "b7",
    slug: "umrah-visa-requirements-2026",
    title: "Umrah Visa Requirements for Sri Lankan Pilgrims (2026 Update)",
    excerpt:
      "How the Umrah e-visa process works for Sri Lankan passport holders — documents, typical processing time, and what your agency handles for you.",
    content: [
      "Most Sri Lankan pilgrims travel to Saudi Arabia today on the Umrah e-visa, issued through Saudi Arabia's Nusuk platform specifically for religious travel — a separate track from Saudi's general tourist e-visa. In practice, you will rarely apply for it yourself: your travel agency submits the Nusuk application as part of your package, using the documents you provide them.",
      "The documents agencies typically ask for are a passport valid for at least six months beyond your travel dates, a recent passport-style photo, your confirmed Umrah booking (return flight and hotel), and your meningococcal ACYW vaccination certificate. Some agencies or, in individual cases, Saudi authorities may also ask to see recent bank statements as proof you can support yourself during the trip — requirements here are not fixed and can vary, so ask your agency exactly what they need from you when you book.",
      "Rules around women travelling without a male mahram have eased significantly in recent years compared to older Umrah visa policies, and organized group travel has made this more straightforward in practice. Even so, policies can vary by agency and individual circumstance, and views on the religious requirement itself differ between scholars — see our separate article on Umrah without a mahram, and always confirm both your agency's current policy and the religious guidance from your own Maulavi before finalizing plans.",
      "Once your documents are submitted, visa processing is usually completed within a matter of days, but it's worth applying as soon as you confirm your package rather than close to departure — processing can slow down during high-demand periods like the weeks before Ramadan.",
      "Saudi visa rules are updated periodically, so treat this article as a general orientation rather than the final word: always confirm the current requirements directly with your booked agency, and use our Umrah Visa Guide tool for a step-by-step walkthrough of the process.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-01",
    status: "published",
  },
  {
    id: "b8",
    slug: "umrah-cost-from-sri-lanka-price-breakdown",
    title: "How Much Does Umrah Cost from Sri Lanka? A Full Price Breakdown",
    excerpt:
      "What actually makes up an Umrah package price — and the extra costs pilgrims often forget to budget for.",
    content: [
      "“How much does Umrah cost?” is one of the first questions every Sri Lankan pilgrim asks, and the honest answer is: it depends heavily on season, hotel distance, flight class and group size. Rather than quote a single number that goes stale the moment prices move, browse current listings on our Umrah Cost in Sri Lanka page, which pulls live minimum, average and maximum prices straight from the packages currently listed by Sri Lankan agencies.",
      "A handful of factors move the price more than anything else: travelling during Ramadan or the weeks around Hajj season costs noticeably more than travelling in quieter months; a hotel a short walk from the Haram costs more than one requiring a shuttle; a direct or business-class flight costs more than a budget one-stop routing; and a smaller, more private group costs more per person than a larger fixed-departure group.",
      "A typical package price bundles together the Umrah visa and agency service fee, return flights, hotel nights split between Makkah and Madinah, and ground transport between the two cities. Some packages fold in a Ziyarah tour of historical sites; others sell it as an add-on, so read the inclusions list carefully rather than comparing sticker prices alone.",
      "Beyond the package price itself, budget separately for costs most pilgrims forget: airport departure taxes, a local SIM card or eSIM for data, meals beyond the breakfast most hotels include, shopping and gifts to bring home, and tips for group guides or porters. Our Umrah Budget Calculator tool walks through these line by line so you can build a realistic total before you commit.",
      "The fairest way to compare two packages is to line them up on duration, hotel distance band and inclusions first, and only then compare the price — a cheaper package with a distant hotel and no Ziyarah isn't necessarily better value than a slightly pricier one that includes both.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-08-22",
    status: "published",
  },
  {
    id: "b9",
    slug: "how-many-days-do-you-need-for-umrah",
    title: "How Many Days Do You Need for Umrah? A Trip-Length Planning Guide",
    excerpt: "From a quick 5-day trip to a relaxed two-week pilgrimage — how to choose the right length for you.",
    content: [
      "Umrah itself — the rites of Ihram, Tawaf, Sa'i and Halq/Taqsir — can be completed in a matter of hours once you're at the Haram. The question of how many days to spend in Saudi Arabia is really about everything around those rites: travel time, rest, additional worship, and how much of Makkah and Madinah you want to see.",
      "At the shorter end, some pilgrims manage a trip of around five to seven days: enough time to perform Umrah, spend a few days in prayer and reflection at both holy mosques, and fit in a short Ziyarah, but with little room for delays or rest days. This works best for pilgrims with travelled before and know what to expect, or who have limited leave from work.",
      "A more common and comfortable range for Sri Lankan pilgrims is ten to fourteen days: a few days settling in and worshipping in Makkah, time in Madinah for prayers at Masjid an-Nabawi and a proper Ziyarah of the historical sites, and enough slack in the schedule to rest, especially in the summer heat.",
      "Trip length also depends on who's travelling. Families with young children or elderly parents often do better with a longer, less rushed itinerary that allows for slower pacing — see our guides on Umrah with children and Umrah for elderly pilgrims for specifics. During Ramadan, especially the last ten nights, availability for longer stays is tighter and in higher demand, so book earlier than you think you need to.",
      "When you're comparing packages on UmrahPackages.lk, use the duration shown on each listing alongside the departure dates to find a trip length that matches your leave, budget and the pace you want — there's no single right answer, only the one that fits your circumstances.",
    ],
    coverImageUrl: BLOG_COVERS.lantern,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-25",
    status: "published",
  },
  {
    id: "b10",
    slug: "can-a-woman-perform-umrah-without-a-mahram",
    title: "Can a Woman Perform Umrah Without a Mahram? What Sri Lankan Pilgrims Should Know",
    excerpt:
      "A general overview of the mahram question for women travelling for Umrah — and why this is a question for your own scholar, not a travel website.",
    content: [
      "This is one of the most commonly searched Umrah questions among Sri Lankan pilgrims, and it sits at the intersection of two different things: what Saudi Arabia's entry rules currently allow, and what Islamic scholarship says a woman should do. This article covers the first in general terms; it is not a religious ruling on the second.",
      "On the practical side, Saudi Arabia's visa and entry policies for women travelling for Umrah have eased substantially compared to older rules, and organized group travel — where a woman travels as part of a supervised tour group rather than alone — has made independent travel more workable in practice for many pilgrims. That said, exact policies can vary by circumstance, and it's worth confirming your specific situation with your travel agency before you book.",
      "On the religious side, scholarly views on whether a woman requires a mahram (a close male relative) to travel for Hajj or Umrah differ, including between different schools of thought, and the details matter — distance travelled, whether she is travelling with a trustworthy group of other women, age, and individual circumstances can all affect the answer given. This is exactly the kind of question that deserves a considered answer from a qualified source, not a generic one from a travel platform.",
      "Practically, many Sri Lankan agencies address this by grouping women travellers together for flights, transfers and shared accommodation within the wider group, and by assigning a group leader or Maulavi who coordinates on-ground logistics. If you're planning to travel without a mahram, ask your agency directly how they handle this before you book — see our guide on choosing the right Umrah agency for what else to check.",
      "This article is presented in general terms and is not affiliated with, or speaking on behalf of, any particular school of thought, sect or organization. For a ruling specific to your own situation, please consult your Maulavi or a qualified religious scholar you trust before making travel decisions on this basis.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Spiritual",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-08-27",
    status: "published",
  },
  {
    id: "b11",
    slug: "economy-vs-luxury-umrah-packages",
    title: "Economy vs. Luxury Umrah Packages: What Actually Changes",
    excerpt: "The rites of Umrah don't change with price — here's exactly what does.",
    content: [
      "Every Umrah package, whatever its price, gives you access to the same rites: the same Ihram, the same Tawaf around the Kaaba, the same Sa'i between Safa and Marwah. What changes as the price goes up isn't the pilgrimage itself, but the comfort and convenience around it.",
      "Economy and standard packages typically mean hotels set further back from the Haram (often relying on a shuttle rather than a short walk), rooms shared between three or four pilgrims, larger tour groups moving on a fixed shared schedule, and economy-class flights, often with a layover. This is where most first-time, budget-conscious Sri Lankan pilgrims start, and it delivers a complete, valid Umrah experience.",
      "Premium and luxury packages shift the comfort dial: hotels directly facing or a short walk from the Haram, double or single room occupancy instead of shared rooms, smaller groups or private transport, more flexibility to set your own pace between prayers, and sometimes business-class flights. None of this is required for a valid Umrah — it's purely about physical comfort and time saved walking or waiting.",
      "So how do you decide? If you're travelling with elderly parents or young children, or if this is a once-in-a-lifetime trip where minimizing walking and fatigue matters, paying for a hotel closer to the Haram is often worth it — see our guides on Umrah for elderly pilgrims and Umrah with children. If you're young, fit and comfortable walking twenty minutes each way, an economy package gets you the same spiritual outcome for meaningfully less money.",
      "Browse our cheap Umrah packages and luxury Umrah packages pages side by side to see exactly how hotel distance, inclusions and price move together across current Sri Lankan agency listings.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-29",
    status: "published",
  },
  {
    id: "b12",
    slug: "flights-colombo-to-saudi-arabia-for-umrah",
    title: "Flights from Colombo to Saudi Arabia for Umrah: Airlines and Routes Explained",
    excerpt: "Direct SriLankan Airlines flights, one-stop Gulf routings, and which Saudi airport to fly into.",
    content: [
      "SriLankan Airlines operates flights from Colombo directly to Jeddah, and at times to Madinah during peak Umrah and Hajj periods, making it the most straightforward option for pilgrims who prefer to avoid a layover. Most agency packages that include flights will book through SriLankan Airlines or a similarly direct option where schedules allow.",
      "One-stop routings through major Gulf hubs are common too, and can sometimes work out cheaper or fit your dates better: flydubai or Emirates via Dubai, Qatar Airways via Doha, Oman Air via Muscat, and Etihad via Abu Dhabi all connect on to Jeddah or Madinah. If you're booking flights independently of a package, comparing a few of these routings on a flight search site is worth the extra few minutes.",
      "Which airport you fly into matters for your itinerary: Jeddah's King Abdulaziz International Airport is the standard entry point and sits roughly one and a half to two hours by road from Makkah, making it the natural choice if your trip starts with Umrah rites first. Prince Mohammad bin Abdulaziz Airport in Madinah is the better entry point if your agency's itinerary starts in Madinah instead. Most Sri Lankan group packages fly into Jeddah, perform Umrah in Makkah, then travel overland to Madinah before flying home from either city.",
      "Fares and schedules shift noticeably around Ramadan and Hajj season as demand spikes, so if you're arranging flights yourself rather than through a bundled package, book earlier than you would for an ordinary holiday and keep an eye on schedule changes in the weeks leading up to departure.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-30",
    status: "published",
  },
  {
    id: "b13",
    slug: "umrah-health-vaccination-requirements",
    title: "Umrah Health and Vaccination Requirements for Sri Lankan Pilgrims",
    excerpt: "The meningitis vaccine timing rule, and the other jabs worth getting before you travel.",
    content: [
      "Saudi Arabia requires all Umrah and Hajj pilgrims aged one year and older to hold a valid meningococcal ACYW vaccination certificate. Timing matters here: the certificate needs to be issued no fewer than ten days before you arrive in Saudi Arabia, and it remains valid for up to three years for the polysaccharide vaccine or five years for the conjugate vaccine, depending on which one you receive. Plan this appointment as one of the first things you do once your travel dates are confirmed, not something to squeeze in the week before you fly.",
      "COVID-19 vaccination or testing requirements for entry have changed repeatedly since 2020 and may be updated again, so check the current rule with your travel agency or the Saudi embassy shortly before departure rather than relying on what was required last year or on what a friend was told.",
      "Beyond what's mandatory, health authorities commonly recommend a seasonal influenza vaccine given how crowded the Haramain get, a polio booster if you haven't had one as an adult, a pneumococcal vaccine for pilgrims aged 65 and above, and general travel vaccines like hepatitis A and B. None of these are unique to Umrah, but the crowded, close-contact nature of the pilgrimage makes them worth discussing with your doctor or a travel clinic.",
      "Health preparation for Umrah isn't only about vaccines. Makkah and Madinah are extremely hot outside the winter months, so pilgrims — especially elderly travellers — should prioritise hydration, sun protection and comfortable, broken-in footwear just as seriously as any injection. Our Makkah & Madinah Weather tool and our guide for elderly pilgrims cover this in more detail.",
      "Because health entry rules are reviewed periodically by Saudi authorities, treat this article as a starting point and confirm the exact current requirements with your agency or the Saudi Ministry of Health close to your departure date.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-01",
    status: "published",
  },
  {
    id: "b14",
    slug: "whats-included-in-an-umrah-package",
    title: "What's Included in an Umrah Package? A Line-by-Line Guide",
    excerpt: "Reading a package listing properly — what's usually bundled in, and what almost always costs extra.",
    content: [
      "Most Umrah packages from Sri Lankan agencies bundle together the same core elements: return flights, the Umrah visa and its processing, hotel accommodation split between Makkah and Madinah, and ground transport between the two cities, often with an orientation briefing on arrival. Beyond that core, exactly what's included starts to vary a lot from one agency to the next.",
      "Commonly excluded, or sold as an optional add-on: a guided Ziyarah tour of historical sites in and around Makkah and Madinah, meals beyond breakfast (most hotels include breakfast, fewer include lunch or dinner), personal expenses like shopping and laundry, tips for group guides or porters, and travel insurance, which is worth adding even when it isn't required for your visa.",
      "The details that matter most when comparing two listings side by side are the hotel names (not just the star rating), how far each hotel actually is from the Haram, whether rooms are shared (quad or triple) or private (double or single), the specific departure and return dates, and the airline and any layovers. Every package listed on UmrahPackages.lk includes these details precisely so pilgrims can compare like-for-like rather than guessing from a headline price.",
      "Before paying any deposit, ask the agency directly — WhatsApp is fine — to confirm in writing exactly what's included and excluded for your specific package. A short question at this stage can prevent an expensive surprise once you're already in Makkah. Our Umrah Budget Calculator and Umrah Visa Guide tools are useful companions for working out what else to plan and budget for beyond the package price itself.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-02",
    status: "published",
  },
  {
    id: "b15",
    slug: "group-family-or-individual-umrah-package",
    title: "Group, Family or Individual Umrah Package: Which Is Right for You?",
    excerpt: "How the three common package formats differ, and how to choose based on who you're travelling with.",
    content: [
      "Group packages are the most common format offered by Sri Lankan agencies: pilgrims travel together on a fixed itinerary and shared schedule, usually with an agency guide or Maulavi coordinating the group throughout. They tend to be the most affordable per person, and the shared structure works well for first-time pilgrims who want a clear schedule and the company of fellow travellers.",
      "Family-oriented packages are built around a family unit rather than a mixed group — think parents travelling with children, or with elderly relatives — with room configurations and pacing adjusted accordingly. These suit families who want more privacy than a large group setup, or who need the flexibility to slow down for a child or an older relative; see our guides on Umrah with children and Umrah for elderly pilgrims for what to look for.",
      "Individual or private packages sit at the other end: private transport, a schedule you set yourself rather than a fixed group itinerary, and the freedom to spend as much or as little time as you like on Ziyarah and personal worship. These come at a higher price point and suit pilgrims who value flexibility over structure, or who are combining Umrah with other personal travel plans.",
      "Worth knowing: most current Sri Lankan agency listings on our platform are organized as group packages, since that's the format most local operators run by default. If you specifically need a family-configured package, use the filters on our Packages page, browse our Family Umrah Packages page, or simply ask an agency directly whether they can arrange a custom family itinerary — many will, even if it isn't their standard listed product.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-03",
    status: "published",
  },
  {
    id: "b16",
    slug: "managing-money-on-umrah-currency-and-budgeting",
    title: "Managing Money on Umrah: Currency, Cash and Budgeting Tips for Sri Lankan Pilgrims",
    excerpt: "What currency to carry, cash vs. cards in Makkah and Madinah, and how to budget for the extras.",
    content: [
      "The Saudi Riyal (SAR) is the standard currency across Makkah and Madinah. While a few vendors near the Haram will informally accept US Dollars or even Sri Lankan Rupees, the exchange rate you'll get is rarely in your favour — it's best to convert to SAR before you travel or shortly after you land.",
      "Exchange rates between the Sri Lankan Rupee and the Saudi Riyal move daily, so rather than plan around a fixed number, compare rates at a couple of licensed money changers in Colombo before you leave, and check a live currency converter — our Islamic Tools section has one — close to your actual travel date so your budget reflects the real rate, not an outdated one.",
      "Cards are increasingly accepted at hotels, larger shops and taxis in both cities, but cash SAR remains essential for smaller vendors, local transport, tipping group guides or porters, and the many small stalls around the Haram. A sensible approach is to carry a mix of both, and to keep a small emergency cash reserve separate from your main wallet in case a card is declined or a machine is out of service.",
      "Beyond the package price, set yourself a daily spending allowance for meals, shopping and any Ziyarah extras, and track it as you go — a small notebook or a notes app on your phone works fine. Keeping a modest reserve on top of that budget covers the unexpected: an extra taxi, a missed hotel meal, or medication you didn't plan for. Our Umrah Budget Calculator tool can help you set this allowance realistically before you fly.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-04",
    status: "published",
  },
];

export const mockMaulavis: Maulavi[] = [
  {
    id: "m1",
    slug: "ustaz-mohamed-rizvi",
    name: "Ustaz Mohamed Rizvi",
    photoUrl: avatar("Rizvi", "0D1B2A"),
    specialization: "Umrah & Hajj Guidance",
    city: "Colombo",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 12,
    phone: "+94 77 111 2233",
    whatsapp: "https://wa.me/94771112233",
  },
  {
    id: "m2",
    slug: "sheikh-abdul-hameed",
    name: "Sheikh Abdul Hameed",
    photoUrl: avatar("Hameed", "C8A24A"),
    specialization: "Fiqh & Pilgrim Counselling",
    city: "Kandy",
    languages: ["Sinhala", "English"],
    yearsExperience: 9,
    phone: "+94 77 222 3344",
    whatsapp: "https://wa.me/94772223344",
  },
  {
    id: "m3",
    slug: "ustaz-fazil-ahamed",
    name: "Ustaz Fazil Ahamed",
    photoUrl: avatar("Fazil", "0D1B2A"),
    specialization: "Ihram Rites & Ziyarah Guidance",
    city: "Kattankudy",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 15,
    phone: "+94 77 333 4455",
    whatsapp: "https://wa.me/94773334455",
  },
  {
    id: "m4",
    slug: "sheikh-nizam-mohideen",
    name: "Sheikh Nizam Mohideen",
    photoUrl: avatar("Nizam", "C8A24A"),
    specialization: "Group Leadership & Pilgrim Counselling",
    city: "Galle",
    languages: ["Sinhala", "Tamil", "English"],
    yearsExperience: 7,
    phone: "+94 77 444 5566",
    whatsapp: "https://wa.me/94774445566",
  },
];

// Inquiries — visible only in the agency/admin dashboards, never on public
// pages. Mix of channels/statuses so the dashboard UI has something to show.
export const mockInquiries: Inquiry[] = [
  {
    id: "i1",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Fathima Rasheed",
    phone: "+94 77 123 4567",
    email: "fathima.r@example.com",
    message: "Is the Nov 12 departure still available for a family of 4?",
    channel: "whatsapp",
    status: "new",
    createdAt: "2026-08-21T09:15:00Z",
  },
  {
    id: "i2",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Mohamed Sadiq",
    phone: "+94 71 987 6543",
    channel: "phone",
    status: "contacted",
    createdAt: "2026-08-19T14:30:00Z",
  },
  {
    id: "i3",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    packageId: "p2",
    packageTitle: "Standard 10-Day Family Umrah Package",
    name: "Aisha Nazeer",
    phone: "+94 76 555 1122",
    email: "aisha.n@example.com",
    message: "Can you split the payment into 3 installments?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T11:05:00Z",
  },
  {
    id: "i4",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    name: "Ismail Farook",
    phone: "+94 77 222 8899",
    channel: "whatsapp",
    status: "closed",
    createdAt: "2026-08-10T08:00:00Z",
  },
  {
    id: "i5",
    agencyId: "a3",
    agencyName: "Baytullah Travels",
    packageId: "p3",
    packageTitle: "Budget 7-Day Umrah Getaway",
    name: "Zainab Hussain",
    phone: "+94 70 333 4455",
    email: "zainab.h@example.com",
    channel: "email",
    status: "contacted",
    createdAt: "2026-08-15T16:45:00Z",
  },
  {
    id: "i6",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    name: "Riyaz Careem",
    phone: "+94 77 666 7788",
    message: "Do you have a package for a solo traveller in December?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T18:20:00Z",
  },
];
