/**
 * PLACEHOLDER DATA — for building and previewing the UI before Supabase
 * is connected. Every query that reads this file today should be swapped
 * for a real Supabase query later (see /supabase/migrations for the
 * matching schema). Search the codebase for "mock-data" when wiring up
 * the database.
 */
import type { Agency, Package, BlogPost, Maulavi, Inquiry } from "@/types/domain";

// Locally generated placeholders (public/placeholders) — no external image
// service dependency during development. Swap for Supabase Storage URLs
// once real photos are uploaded.
const AGENCY_LOGOS: Record<string, string> = {
  "NM Travels": "/placeholders/logo-nm-travels.png",
  "Zaid Travels": "/placeholders/logo-zaid.png",
  "Akbar Travels": "/placeholders/logo-akbar.png",
  "SMS Travels": "/placeholders/logo-sms.png",
};
// `..._rest` soaks up the old (seed, bg) / (seed) call sites below without
// needing to touch every call — the values were only ever used to pick a
// deterministic-looking placeholder, which the lookup table / cycle already do.
const avatar = (seed: string, ..._rest: unknown[]) =>
  AGENCY_LOGOS[seed] ?? "/placeholders/logo-nm-travels.png";

// 9 visually distinct icons (gate, dome+minarets, Kaaba, crescent+star, flight
// path, tasbih beads, qibla compass, suitcase, passport+ticket) — one per
// current agency/package below, so no two cards show the identical cover.
const COVER_IMAGES = [
  "/placeholders/cover-1.jpg",
  "/placeholders/cover-2.jpg",
  "/placeholders/cover-3.jpg",
  "/placeholders/cover-4.jpg",
  "/placeholders/cover-5.jpg",
  "/placeholders/cover-6.jpg",
  "/placeholders/cover-7.jpg",
  "/placeholders/cover-8.jpg",
  "/placeholders/cover-9.jpg",
];
let coverIndex = 0;
const cover = (..._rest: unknown[]) => {
  const img = COVER_IMAGES[coverIndex % COVER_IMAGES.length];
  coverIndex += 1;
  return img;
};

// Blog posts get their own dedicated pool of covers (distinct line-art
// motifs — crescent & star, mosque dome, compass, lantern, etc. — instead
// of sharing the small agency/package cover pool above, which made
// adjacent blog cards look like duplicates of each other). Each post picks
// its cover explicitly rather than cycling, so the motif can loosely match
// the article's topic.
const BLOG_COVERS = {
  crescentStar: "/placeholders/blog-cover-1.jpg",
  mosque: "/placeholders/blog-cover-2.jpg",
  compass: "/placeholders/blog-cover-3.jpg",
  lantern: "/placeholders/blog-cover-4.jpg",
  suitcase: "/placeholders/blog-cover-5.jpg",
  calendar: "/placeholders/blog-cover-6.jpg",
  tasbih: "/placeholders/blog-cover-7.jpg",
  paperPlane: "/placeholders/blog-cover-8.jpg",
} as const;

// Real agencies, sourced from their own public Facebook/Meta ad creatives
// (screenshotted by the site owner 2026-09). No rating/badges/years are set
// unless the ad itself stated them — this platform never invents trust
// signals for a real business (see travelAgencySchema's note on
// aggregateRating). Logos are simple generated monograms (not the agency's
// actual brand logo) until real logo files are supplied.
export const mockAgencies: Agency[] = [
  {
    id: "a1",
    slug: "nm-travels-tours",
    name: "NM Travels & Tours PVT LTD",
    logoUrl: avatar("NM Travels"),
    coverImageUrl: cover("nm"),
    description:
      "Umrah & Hajj operator based in Wellawatte, Colombo. IATA member and Saudi Hajj Ministry-approved organization, running group Umrah departures with full-board Sri Lankan meals.",
    city: "Colombo",
    address: "#573, Habib Bank Building, Galle Road, Wellawatte, Colombo 06",
    phone: "+94 71 279 9648",
    whatsapp: "https://wa.me/94712799648",
    badges: [],
    packageCount: 2,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a2",
    slug: "zaid-travels-tours",
    name: "Zaid Travels & Tours (PVT) LTD",
    logoUrl: avatar("Zaid Travels"),
    coverImageUrl: cover("zaid"),
    description:
      "Umrah operator on Mosque Road, Beruwala, running a fixed premium 11-day departure with hotels close to Haram and Masjid Nabawi, and 3 Umrahs included.",
    city: "Beruwala",
    address: "Mosque Road, Beruwala",
    phone: "+94 76 738 4104",
    whatsapp: "https://wa.me/94767384104",
    badges: [],
    packageCount: 1,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a3",
    slug: "akbar-travels-and-tours",
    name: "Akbar Travels and Tours (PVT) LTD",
    logoUrl: avatar("Akbar Travels"),
    coverImageUrl: cover("akbar"),
    description:
      "IATA-accredited Umrah operator in Wellampitiya, Colombo, marking its 10th anniversary with September–November 2026 departures on Etihad Airways and SalamAir, staying at named Makkah and Madinah hotels.",
    city: "Colombo",
    address: "119/18, Megoda Kolonnawa Road, Wellampitiya",
    phone: "+94 76 694 5592",
    whatsapp: "https://wa.me/94716370349",
    badges: [],
    yearsActive: 10,
    packageCount: 3,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a4",
    slug: "sms-travels-tours",
    name: "SMS Travels & Tours (Pvt) Ltd",
    logoUrl: avatar("SMS Travels"),
    coverImageUrl: cover("sms"),
    description:
      "17+ year Umrah operator in Maradana, Colombo (CAA Sri Lanka & IATA approved), offering four package tiers — Normal to Platinum — across the same set of September 2026 departure dates.",
    city: "Colombo",
    address: "19/20 Abdullah Building, Symonds Road, Maradana, Colombo 10",
    phone: "+94 77 616 2323",
    whatsapp: "https://wa.me/94776162323",
    badges: [],
    yearsActive: 17,
    packageCount: 4,
    isActive: true,
    createdAt: "2026-09-03",
  },
];

// Real packages, transcribed from the same agency ad screenshots as
// mockAgencies above. Where an ad didn't state a specific fact (an airline,
// a named hotel, a star rating), that field says so honestly instead of
// guessing — see the optional makkahHotelStars/madinahHotelStars/email
// fields on the Agency/Package types. Engagement counts (view/click/etc.)
// start at 0 — these are brand-new real listings with no platform history
// yet, not carried-over demo traffic.
export const mockPackages: Package[] = [
  {
    id: "p1",
    slug: "nm-umrah-11-day-sept-20-early",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Early Group Departure (Sept 20)",
    coverImageUrl: cover("pkg1"),
    images: [cover("pkg1a")],
    priceLkr: 339000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-20"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p2",
    slug: "nm-umrah-11-day-sept-group",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Group Departure (Sept 12 & 26)",
    coverImageUrl: cover("pkg2"),
    images: [cover("pkg2a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-12", "2026-09-26"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p3",
    slug: "zaid-premium-11-day-oct-22",
    agencyId: "a2",
    agency: mockAgencies[1],
    title: "Premium 11-Day Umrah Package (22 Oct Departure)",
    coverImageUrl: cover("pkg3"),
    images: [cover("pkg3a")],
    priceLkr: 375000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Makkah hotel 500m from Haram (name TBA — confirm with agency)",
    madinahHotel: "Madinah hotel 300m from Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan meals",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "3 Umrahs included",
      "Ziyarah tours",
      "Sri Lankan meals",
      "Guide",
      "Free Jorana & Badr tour",
    ],
    exclusions: [],
    departureDates: ["2026-10-22"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p4",
    slug: "akbar-umrah-10-day-sept-16-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Sept 16 Departure (Etihad Airways)",
    coverImageUrl: cover("pkg4"),
    images: [cover("pkg4a")],
    priceLkr: 350000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p5",
    slug: "akbar-umrah-11-day-sept-16-salamair",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "11-Day Umrah — Sept 16 Departure (SalamAir)",
    coverImageUrl: cover("pkg5"),
    images: [cover("pkg5a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "SalamAir",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (SalamAir)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p6",
    slug: "akbar-umrah-10-day-oct-nov-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Oct 22 / Nov 19 Departures (Etihad Airways)",
    coverImageUrl: cover("pkg6"),
    images: [cover("pkg6a")],
    priceLkr: 360000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-10-22", "2026-11-19"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p7",
    slug: "sms-umrah-normal-10-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Normal Package — 10-Day Umrah",
    coverImageUrl: cover("pkg7"),
    images: [cover("pkg7a")],
    priceLkr: 349000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "economy",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p8",
    slug: "sms-umrah-silver-12-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Silver Package — 12-Day Umrah",
    coverImageUrl: cover("pkg8"),
    images: [cover("pkg8a")],
    priceLkr: 379000,
    durationDays: 12,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p9",
    slug: "sms-umrah-golden-15-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Golden Package — 15-Day Umrah",
    coverImageUrl: cover("pkg9"),
    images: [cover("pkg9a")],
    priceLkr: 399000,
    durationDays: 15,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p10",
    slug: "sms-umrah-platinum-18-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Platinum Package — 18-Day Umrah",
    coverImageUrl: cover("pkg10"),
    images: [cover("pkg10a")],
    priceLkr: 469000,
    durationDays: 18,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "first-time-umrah-checklist",
    title: "First-Time Umrah: The Complete Pre-Departure Checklist",
    excerpt:
      "Everything Sri Lankan pilgrims need to prepare — documents, packing, health requirements, and etiquette — before their first Umrah journey.",
    content: [
      "Performing Umrah for the first time is a deeply emotional milestone, and a little preparation goes a long way toward making the journey smooth and stress-free. This checklist covers the essentials every Sri Lankan pilgrim should sort out before departure.",
      "Documents first: make sure your passport has at least six months of validity remaining, and confirm your Umrah visa has been processed by your travel agency well ahead of departure. Keep printed and digital copies of your passport, visa, vaccination certificate, and flight tickets in a separate folder from the originals.",
      "Health requirements for Umrah typically include a Meningitis (ACYW135) vaccination certificate, valid for the period specified by Saudi health authorities, and seasonal requirements such as flu vaccination during certain periods. Check with your agency for the latest requirements, as these are updated periodically by the Saudi Ministry of Hajj and Umrah.",
      "Packing for Umrah is different from typical travel. Men should pack at least two sets of Ihram cloth (unstitched white garments) along with a money belt, and comfortable slip-on sandals for the many trips in and out of the mosque. Women should pack loose, modest clothing in breathable fabrics, and a comfortable pair of walking shoes — you will be on your feet far more than you expect.",
      "Finally, take time to learn the basic rites and duas of Umrah before you travel — Ihram, Tawaf, Sa'i, and Halq/Taqsir — so that you can focus on the spiritual experience rather than fumbling through the sequence on the day. Most reputable agencies provide a pre-departure briefing; attend it even if you've researched independently.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-07-20",
    status: "published",
  },
  {
    id: "b2",
    slug: "best-time-to-perform-umrah",
    title: "When Is the Best Time to Perform Umrah? A Season-by-Season Guide",
    excerpt:
      "Comparing crowd levels, weather, and pricing across Ramadan, Hajj season, and the rest of the year.",
    content: [
      "Umrah can be performed at any time of the year, but when you choose to go significantly affects crowd levels, weather, and the price of your package. Here's how the year generally breaks down for Sri Lankan pilgrims.",
      "Ramadan is the most spiritually rewarding time to perform Umrah, with the reward said to be equivalent to Hajj in virtue. It is also, unsurprisingly, the busiest and most expensive period — expect significantly higher package prices and larger crowds at the Haramain, especially in the last ten nights.",
      "The months immediately after Hajj (roughly Muharram through Safar) tend to be quieter and more affordable, as the post-Hajj rush has settled and Ramadan demand hasn't yet begun. This is often the best balance of comfortable crowd levels and reasonable pricing.",
      "Weather-wise, Makkah and Madinah are extremely hot from May through September, often exceeding 40°C. Pilgrims with health conditions, older family members, or young children may prefer the cooler months from November to February.",
      "If budget is the primary concern, avoid school holiday periods (which drive up demand from other countries) and Ramadan. Compare a few packages across different months on UmrahPackages.lk to see how much the timing itself moves the price.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-06-05",
    status: "published",
  },
  {
    id: "b3",
    slug: "umrah-dua-guide",
    title: "Essential Duas for Every Step of Umrah",
    excerpt: "A pilgrim's pocket guide to the key duas for Tawaf, Sa'i, and Ihram.",
    content: [
      "While there is no single obligatory dua for each step of Umrah — you may supplicate in your own words and language — there are well-known duas the Prophet ﷺ and his companions are reported to have recited, and learning them adds structure and meaning to each rite.",
      "Entering Ihram: recite the Talbiyah repeatedly from the moment you enter the state of Ihram until you begin Tawaf: 'Labbayk Allahumma labbayk, labbayka la sharika laka labbayk...' ('Here I am, O Allah, here I am. Here I am, You have no partner, here I am...').",
      "During Tawaf: there is no fixed dua for each circuit — pilgrims commonly recite the dua between the Yemeni Corner and the Black Stone: 'Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar' ('Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire').",
      "During Sa'i: while walking between Safa and Marwah, pilgrims often recite Qur'anic verses and personal supplications freely — this is an excellent time for heartfelt, personal dua in your own language.",
      "After Halq/Taqsir: once the hair is cut or trimmed and Umrah is complete, it is customary to thank Allah and make dua for acceptance of the pilgrimage. Our Islamic Tools page has a Dua of the Day feature if you'd like to continue building a habit of daily supplication after you return home.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Spiritual",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 10,
    publishedAt: "2026-05-18",
    status: "published",
  },
  {
    id: "b4",
    slug: "choosing-the-right-umrah-agency",
    title: "How to Choose the Right Umrah Travel Agency in Sri Lanka",
    excerpt:
      "What to check before you commit — licensing, reviews, itinerary transparency, and red flags to avoid.",
    content: [
      "With dozens of travel agencies in Sri Lanka offering Umrah packages, choosing the right one can feel overwhelming. Here's a practical checklist to work through before you commit.",
      "Verify licensing first. A legitimate Umrah operator should be registered and able to show proof of their travel agency license and any relevant IATA or SLTDA registration. Gold Verified and Premium Partner badges on UmrahPackages.lk are only issued after this kind of vetting.",
      "Read the itinerary line by line. A trustworthy agency will clearly state hotel names (not just star ratings), distance from the Haram, flight routing and layovers, and exactly what's included versus what costs extra (visa fees, Ziyarah tours, meals).",
      "Ask about the on-ground team. Reputable agencies have a dedicated coordinator or guide (often a Maulavi) accompanying or based in Makkah and Madinah who can assist with logistics and religious guidance during your stay.",
      "Be cautious of prices that are dramatically below the market average — this is often a sign of hidden costs, downgraded hotels after booking, or, in rare cases, outright scams. Compare a handful of packages side by side on our Compare page before making a decision, and always confirm final details directly with the agency over WhatsApp or phone.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-04-10",
    status: "published",
  },
  {
    id: "b5",
    slug: "umrah-packing-list-for-women",
    title: "The Complete Umrah Packing List for Women",
    excerpt: "Modest, comfortable, and practical — everything Sri Lankan women should pack for Umrah.",
    content: [
      "Packing for Umrah as a woman is about balancing modesty, comfort, and practicality for long days of walking and standing. Here is a complete list to work from.",
      "Clothing: pack loose-fitting, non-see-through abayas or modest outfits in breathable fabrics — cotton blends handle the heat far better than synthetic materials. Bring at least one dedicated white or light-colored outfit that meets Ihram conditions if your madhab/family custom calls for it, plus a few headscarves in easy-to-tie styles.",
      "Footwear: comfortable, well broken-in walking shoes are non-negotiable — you'll easily walk 15,000+ steps a day between the hotel, the Haram, and Sa'i. Pack a lightweight pair of sandals for inside the mosque.",
      "Toiletries: unscented soap and wudhu-friendly products (scented items are discouraged in the state of Ihram), a small first-aid kit, and any personal medication clearly labeled with your name.",
      "Extras worth packing: a small prayer mat or mat cover for airport/layover prayers, a portable charger, a lightweight shawl for air-conditioned mosque halls, and a few zip-lock bags for damp or dusty items on the way home.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-03-02",
    status: "published",
  },
  {
    id: "b6",
    slug: "umrah-vs-hajj-whats-the-difference",
    title: "Umrah vs. Hajj: What's the Difference?",
    excerpt: "A clear, simple breakdown of how Umrah and Hajj differ in timing, rites, and obligation.",
    content: [
      "Umrah and Hajj are both pilgrimages to Makkah, and they share several rites, but they differ in timing, obligation, and scale. Understanding the difference helps first-time pilgrims plan the right journey for their circumstances.",
      "Timing: Hajj can only be performed during a specific window in the Islamic calendar — the 8th to 13th of Dhu al-Hijjah. Umrah, on the other hand, can be performed at any time of the year, which is why it's often called the 'minor pilgrimage.'",
      "Obligation: Hajj is one of the Five Pillars of Islam and is obligatory once in a lifetime for every Muslim who is physically and financially able. Umrah is highly recommended (sunnah mu'akkadah in most views) but not obligatory in the same way.",
      "Rites: Hajj includes all the rites of Umrah (Ihram, Tawaf, Sa'i) plus additional rites unique to it — standing at Arafah, staying overnight at Muzdalifah and Mina, and the symbolic stoning of the Jamarat. Umrah is a shorter set of rites that can typically be completed within a few hours.",
      "Scale: Hajj draws several million pilgrims within the same short window each year, making logistics and crowd management far more complex than Umrah, which spreads pilgrims across the entire year.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 5,
    publishedAt: "2026-02-14",
    status: "published",
  },
  {
    id: "b7",
    slug: "umrah-visa-requirements-2026",
    title: "Umrah Visa Requirements for Sri Lankan Pilgrims (2026 Update)",
    excerpt: "A draft explainer on the latest Umrah visa requirements — pending an editorial review before publishing.",
    content: [
      "This article is still being drafted — check back soon for a full breakdown of current Umrah visa requirements for Sri Lankan passport holders.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 4,
    publishedAt: "2026-08-20",
    status: "draft",
  },
];

export const mockMaulavis: Maulavi[] = [
  {
    id: "m1",
    slug: "ustaz-mohamed-rizvi",
    name: "Ustaz Mohamed Rizvi",
    photoUrl: avatar("Rizvi", "0D1B2A"),
    specialization: "Umrah & Hajj Guidance",
    city: "Colombo",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 12,
    phone: "+94 77 111 2233",
    whatsapp: "https://wa.me/94771112233",
  },
  {
    id: "m2",
    slug: "sheikh-abdul-hameed",
    name: "Sheikh Abdul Hameed",
    photoUrl: avatar("Hameed", "C8A24A"),
    specialization: "Fiqh & Pilgrim Counselling",
    city: "Kandy",
    languages: ["Sinhala", "English"],
    yearsExperience: 9,
    phone: "+94 77 222 3344",
    whatsapp: "https://wa.me/94772223344",
  },
  {
    id: "m3",
    slug: "ustaz-fazil-ahamed",
    name: "Ustaz Fazil Ahamed",
    photoUrl: avatar("Fazil", "0D1B2A"),
    specialization: "Ihram Rites & Ziyarah Guidance",
    city: "Kattankudy",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 15,
    phone: "+94 77 333 4455",
    whatsapp: "https://wa.me/94773334455",
  },
  {
    id: "m4",
    slug: "sheikh-nizam-mohideen",
    name: "Sheikh Nizam Mohideen",
    photoUrl: avatar("Nizam", "C8A24A"),
    specialization: "Group Leadership & Pilgrim Counselling",
    city: "Galle",
    languages: ["Sinhala", "Tamil", "English"],
    yearsExperience: 7,
    phone: "+94 77 444 5566",
    whatsapp: "https://wa.me/94774445566",
  },
];

// Inquiries — visible only in the agency/admin dashboards, never on public
// pages. Mix of channels/statuses so the dashboard UI has something to show.
export const mockInquiries: Inquiry[] = [
  {
    id: "i1",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Fathima Rasheed",
    phone: "+94 77 123 4567",
    email: "fathima.r@example.com",
    message: "Is the Nov 12 departure still available for a family of 4?",
    channel: "whatsapp",
    status: "new",
    createdAt: "2026-08-21T09:15:00Z",
  },
  {
    id: "i2",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Mohamed Sadiq",
    phone: "+94 71 987 6543",
    channel: "phone",
    status: "contacted",
    createdAt: "2026-08-19T14:30:00Z",
  },
  {
    id: "i3",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    packageId: "p2",
    packageTitle: "Standard 10-Day Family Umrah Package",
    name: "Aisha Nazeer",
    phone: "+94 76 555 1122",
    email: "aisha.n@example.com",
    message: "Can you split the payment into 3 installments?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T11:05:00Z",
  },
  {
    id: "i4",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    name: "Ismail Farook",
    phone: "+94 77 222 8899",
    channel: "whatsapp",
    status: "closed",
    createdAt: "2026-08-10T08:00:00Z",
  },
  {
    id: "i5",
    agencyId: "a3",
    agencyName: "Baytullah Travels",
    packageId: "p3",
    packageTitle: "Budget 7-Day Umrah Getaway",
    name: "Zainab Hussain",
    phone: "+94 70 333 4455",
    email: "zainab.h@example.com",
    channel: "email",
    status: "contacted",
    createdAt: "2026-08-15T16:45:00Z",
  },
  {
    id: "i6",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    name: "Riyaz Careem",
    phone: "+94 77 666 7788",
    message: "Do you have a package for a solo traveller in December?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T18:20:00Z",
  },
];
