/**
 * PLACEHOLDER DATA — for building and previewing the UI before Supabase
 * is connected. Every query that reads this file today should be swapped
 * for a real Supabase query later (see /supabase/migrations for the
 * matching schema). Search the codebase for "mock-data" when wiring up
 * the database.
 */
import type { Agency, Package, BlogPost, Maulavi, Inquiry } from "@/types/domain";

// Locally generated placeholders (public/placeholders) — no external image
// service dependency during development. Swap for Supabase Storage URLs
// once real photos are uploaded.
const AGENCY_LOGOS: Record<string, string> = {
  "NM Travels": "/placeholders/logo-nm-travels.png",
  "Zaid Travels": "/placeholders/logo-zaid.png",
  "Akbar Travels": "/placeholders/logo-akbar.png",
  "SMS Travels": "/placeholders/logo-sms.png",
};
// `..._rest` soaks up the old (seed, bg) / (seed) call sites below without
// needing to touch every call — the values were only ever used to pick a
// deterministic-looking placeholder, which the lookup table / cycle already do.
const avatar = (seed: string, ..._rest: unknown[]) =>
  AGENCY_LOGOS[seed] ?? "/placeholders/logo-nm-travels.png";

// 9 visually distinct icons (gate, dome+minarets, Kaaba, crescent+star, flight
// path, tasbih beads, qibla compass, suitcase, passport+ticket) — one per
// current agency/package below, so no two cards show the identical cover.
const COVER_IMAGES = [
  "/placeholders/cover-1.jpg",
  "/placeholders/cover-2.jpg",
  "/placeholders/cover-3.jpg",
  "/placeholders/cover-4.jpg",
  "/placeholders/cover-5.jpg",
  "/placeholders/cover-6.jpg",
  "/placeholders/cover-7.jpg",
  "/placeholders/cover-8.jpg",
  "/placeholders/cover-9.jpg",
];
let coverIndex = 0;
const cover = (..._rest: unknown[]) => {
  const img = COVER_IMAGES[coverIndex % COVER_IMAGES.length];
  coverIndex += 1;
  return img;
};

// Blog posts get their own dedicated pool of covers (distinct line-art
// motifs — crescent & star, mosque dome, compass, lantern, etc. — instead
// of sharing the small agency/package cover pool above, which made
// adjacent blog cards look like duplicates of each other). Each post picks
// its cover explicitly rather than cycling, so the motif can loosely match
// the article's topic.
const BLOG_COVERS = {
  crescentStar: "/placeholders/blog-cover-1.jpg",
  mosque: "/placeholders/blog-cover-2.jpg",
  compass: "/placeholders/blog-cover-3.jpg",
  lantern: "/placeholders/blog-cover-4.jpg",
  suitcase: "/placeholders/blog-cover-5.jpg",
  calendar: "/placeholders/blog-cover-6.jpg",
  tasbih: "/placeholders/blog-cover-7.jpg",
  paperPlane: "/placeholders/blog-cover-8.jpg",
} as const;

// Real agencies, sourced from their own public Facebook/Meta ad creatives
// (screenshotted by the site owner 2026-09). No rating/badges/years are set
// unless the ad itself stated them — this platform never invents trust
// signals for a real business (see travelAgencySchema's note on
// aggregateRating). Logos are simple generated monograms (not the agency's
// actual brand logo) until real logo files are supplied.
export const mockAgencies: Agency[] = [
  {
    id: "a1",
    slug: "nm-travels-tours",
    name: "NM Travels & Tours PVT LTD",
    logoUrl: avatar("NM Travels"),
    coverImageUrl: cover("nm"),
    description:
      "Umrah & Hajj operator based in Wellawatte, Colombo. IATA member and Saudi Hajj Ministry-approved organization, running group Umrah departures with full-board Sri Lankan meals.",
    city: "Colombo",
    address: "#573, Habib Bank Building, Galle Road, Wellawatte, Colombo 06",
    phone: "+94 71 279 9648",
    whatsapp: "https://wa.me/94712799648",
    badges: [],
    packageCount: 2,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a2",
    slug: "zaid-travels-tours",
    name: "Zaid Travels & Tours (PVT) LTD",
    logoUrl: avatar("Zaid Travels"),
    coverImageUrl: cover("zaid"),
    description:
      "Umrah operator on Mosque Road, Beruwala, running a fixed premium 11-day departure with hotels close to Haram and Masjid Nabawi, and 3 Umrahs included.",
    city: "Beruwala",
    address: "Mosque Road, Beruwala",
    phone: "+94 76 738 4104",
    whatsapp: "https://wa.me/94767384104",
    badges: [],
    packageCount: 1,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a3",
    slug: "akbar-travels-and-tours",
    name: "Akbar Travels and Tours (PVT) LTD",
    logoUrl: avatar("Akbar Travels"),
    coverImageUrl: cover("akbar"),
    description:
      "IATA-accredited Umrah operator in Wellampitiya, Colombo, marking its 10th anniversary with September–November 2026 departures on Etihad Airways and SalamAir, staying at named Makkah and Madinah hotels.",
    city: "Colombo",
    address: "119/18, Megoda Kolonnawa Road, Wellampitiya",
    phone: "+94 76 694 5592",
    whatsapp: "https://wa.me/94716370349",
    badges: [],
    yearsActive: 10,
    packageCount: 3,
    isActive: true,
    createdAt: "2026-09-03",
  },
  {
    id: "a4",
    slug: "sms-travels-tours",
    name: "SMS Travels & Tours (Pvt) Ltd",
    logoUrl: avatar("SMS Travels"),
    coverImageUrl: cover("sms"),
    description:
      "17+ year Umrah operator in Maradana, Colombo (CAA Sri Lanka & IATA approved), offering four package tiers — Normal to Platinum — across the same set of September 2026 departure dates.",
    city: "Colombo",
    address: "19/20 Abdullah Building, Symonds Road, Maradana, Colombo 10",
    phone: "+94 77 616 2323",
    whatsapp: "https://wa.me/94776162323",
    badges: [],
    yearsActive: 17,
    packageCount: 4,
    isActive: true,
    createdAt: "2026-09-03",
  },
];

// Real packages, transcribed from the same agency ad screenshots as
// mockAgencies above. Where an ad didn't state a specific fact (an airline,
// a named hotel, a star rating), that field says so honestly instead of
// guessing — see the optional makkahHotelStars/madinahHotelStars/email
// fields on the Agency/Package types. Engagement counts (view/click/etc.)
// start at 0 — these are brand-new real listings with no platform history
// yet, not carried-over demo traffic.
export const mockPackages: Package[] = [
  {
    id: "p1",
    slug: "nm-umrah-11-day-sept-20-early",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Early Group Departure (Sept 20)",
    coverImageUrl: cover("pkg1"),
    images: [cover("pkg1a")],
    priceLkr: 339000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-20"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p2",
    slug: "nm-umrah-11-day-sept-group",
    agencyId: "a1",
    agency: mockAgencies[0],
    title: "11-Day Umrah — Group Departure (Sept 12 & 26)",
    coverImageUrl: cover("pkg2"),
    images: [cover("pkg2a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Millennium Hotel Makkah",
    makkahHotelStars: 5,
    madinahHotel: "Grand Hotel Madinah",
    madinahHotelStars: 4,
    mealPlan: "Full Board (Sri Lankan meals, buffet)",
    transport: "Included",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "full-board"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "5★ Makkah hotel (Millennium)",
      "4★ Madinah hotel (Grand Hotel)",
      "Full board Sri Lankan meals",
      "Guided by experienced ulama",
    ],
    exclusions: [],
    departureDates: ["2026-09-12", "2026-09-26"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p3",
    slug: "zaid-premium-11-day-oct-22",
    agencyId: "a2",
    agency: mockAgencies[1],
    title: "Premium 11-Day Umrah Package (22 Oct Departure)",
    coverImageUrl: cover("pkg3"),
    images: [cover("pkg3a")],
    priceLkr: 375000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Makkah hotel 500m from Haram (name TBA — confirm with agency)",
    madinahHotel: "Madinah hotel 300m from Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan meals",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa",
      "3 Umrahs included",
      "Ziyarah tours",
      "Sri Lankan meals",
      "Guide",
      "Free Jorana & Badr tour",
    ],
    exclusions: [],
    departureDates: ["2026-10-22"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p4",
    slug: "akbar-umrah-10-day-sept-16-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Sept 16 Departure (Etihad Airways)",
    coverImageUrl: cover("pkg4"),
    images: [cover("pkg4a")],
    priceLkr: 350000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p5",
    slug: "akbar-umrah-11-day-sept-16-salamair",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "11-Day Umrah — Sept 16 Departure (SalamAir)",
    coverImageUrl: cover("pkg5"),
    images: [cover("pkg5a")],
    priceLkr: 350000,
    durationDays: 11,
    departureCity: "Colombo (CMB)",
    airline: "SalamAir",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (SalamAir)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-09-16"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p6",
    slug: "akbar-umrah-10-day-oct-nov-etihad",
    agencyId: "a3",
    agency: mockAgencies[2],
    title: "10-Day Umrah — Oct 22 / Nov 19 Departures (Etihad Airways)",
    coverImageUrl: cover("pkg6"),
    images: [cover("pkg6a")],
    priceLkr: 360000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "Etihad Airways",
    makkahHotel: "Tawheed Al Asala",
    madinahHotel: "Al Bustan Diamond",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare (Etihad Airways)",
      "Umrah visa",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "Makkah city tour",
      "Badr visit",
      "Makkah hotel 500m from Haram (Tawheed Al Asala)",
      "Madinah hotel 150m from Masjid Nabawi (Al Bustan Diamond)",
      "10% discount for children under 5",
    ],
    exclusions: [],
    departureDates: ["2026-10-22", "2026-11-19"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p7",
    slug: "sms-umrah-normal-10-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Normal Package — 10-Day Umrah",
    coverImageUrl: cover("pkg7"),
    images: [cover("pkg7a")],
    priceLkr: 349000,
    durationDays: 10,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "economy",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p8",
    slug: "sms-umrah-silver-12-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Silver Package — 12-Day Umrah",
    coverImageUrl: cover("pkg8"),
    images: [cover("pkg8a")],
    priceLkr: 379000,
    durationDays: 12,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p9",
    slug: "sms-umrah-golden-15-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Golden Package — 15-Day Umrah",
    coverImageUrl: cover("pkg9"),
    images: [cover("pkg9a")],
    priceLkr: 399000,
    durationDays: 15,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "standard",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
  {
    id: "p10",
    slug: "sms-umrah-platinum-18-day",
    agencyId: "a4",
    agency: mockAgencies[3],
    title: "Platinum Package — 18-Day Umrah",
    coverImageUrl: cover("pkg10"),
    images: [cover("pkg10a")],
    priceLkr: 469000,
    durationDays: 18,
    departureCity: "Colombo (CMB)",
    airline: "TBA (confirm with agency)",
    makkahHotel: "Hotel near Haram (name TBA — confirm with agency)",
    madinahHotel: "Hotel near Masjid Nabawi (name TBA — confirm with agency)",
    mealPlan: "Sri Lankan buffet",
    transport: "VIP transport",
    visaIncluded: true,
    groupType: "group",
    category: "premium",
    tags: ["group-departure", "3-umrah"],
    inclusions: [
      "Return airfare",
      "Umrah visa processing",
      "2 Jumu'ah prayers",
      "3 Umrahs",
      "VIP transport",
      "Ziyarah tours",
      "Sri Lankan buffet meals",
      "Experienced guide",
      "24/7 support",
    ],
    exclusions: [],
    departureDates: ["2026-09-09", "2026-09-10", "2026-09-16", "2026-09-17", "2026-09-23", "2026-09-24"],
    viewCount: 0,
    clickCount: 0,
    compareCount: 0,
    contactCount: 0,
    isFeatured: false,
    isPublished: true,
    createdAt: "2026-09-03",
    updatedAt: "2026-09-03",
  },
];

export const mockBlogPosts: BlogPost[] = [
  {
    id: "b1",
    slug: "first-time-umrah-checklist",
    title: "First-Time Umrah: The Complete Pre-Departure Checklist",
    excerpt:
      "Everything Sri Lankan pilgrims need to prepare — documents, packing, health requirements, and etiquette — before their first Umrah journey.",
    content: [
      "Performing Umrah for the first time is a deeply emotional milestone, and a little preparation goes a long way toward making the journey smooth and stress-free. This checklist covers the essentials every Sri Lankan pilgrim should sort out before departure.",
      "Documents first: make sure your passport has at least six months of validity remaining, and confirm your Umrah visa has been processed by your travel agency well ahead of departure. Keep printed and digital copies of your passport, visa, vaccination certificate, and flight tickets in a separate folder from the originals.",
      "Health requirements for Umrah typically include a Meningitis (ACYW135) vaccination certificate, valid for the period specified by Saudi health authorities, and seasonal requirements such as flu vaccination during certain periods. Check with your agency for the latest requirements, as these are updated periodically by the Saudi Ministry of Hajj and Umrah.",
      "Packing for Umrah is different from typical travel. Men should pack at least two sets of Ihram cloth (unstitched white garments) along with a money belt, and comfortable slip-on sandals for the many trips in and out of the mosque. Women should pack loose, modest clothing in breathable fabrics, and a comfortable pair of walking shoes — you will be on your feet far more than you expect.",
      "Finally, take time to learn the basic rites and duas of Umrah before you travel — Ihram, Tawaf, Sa'i, and Halq/Taqsir — so that you can focus on the spiritual experience rather than fumbling through the sequence on the day. Most reputable agencies provide a pre-departure briefing; attend it even if you've researched independently.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-07-20",
    status: "published",
  },
  {
    id: "b2",
    slug: "best-time-to-perform-umrah",
    title: "When Is the Best Time to Perform Umrah? A Season-by-Season Guide",
    excerpt:
      "Comparing crowd levels, weather, and pricing across Ramadan, Hajj season, and the rest of the year.",
    content: [
      "Umrah can be performed at any time of the year, but when you choose to go significantly affects crowd levels, weather, and the price of your package. Here's how the year generally breaks down for Sri Lankan pilgrims.",
      "Ramadan is the most spiritually rewarding time to perform Umrah, with the reward said to be equivalent to Hajj in virtue. It is also, unsurprisingly, the busiest and most expensive period — expect significantly higher package prices and larger crowds at the Haramain, especially in the last ten nights.",
      "The months immediately after Hajj (roughly Muharram through Safar) tend to be quieter and more affordable, as the post-Hajj rush has settled and Ramadan demand hasn't yet begun. This is often the best balance of comfortable crowd levels and reasonable pricing.",
      "Weather-wise, Makkah and Madinah are extremely hot from May through September, often exceeding 40°C. Pilgrims with health conditions, older family members, or young children may prefer the cooler months from November to February.",
      "If budget is the primary concern, avoid school holiday periods (which drive up demand from other countries) and Ramadan. Compare a few packages across different months on UmrahPackages.lk to see how much the timing itself moves the price.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-06-05",
    status: "published",
  },
  {
    id: "b3",
    slug: "umrah-dua-guide",
    title: "Essential Duas for Every Step of Umrah",
    excerpt: "A pilgrim's pocket guide to the key duas for Tawaf, Sa'i, and Ihram.",
    content: [
      "While there is no single obligatory dua for each step of Umrah — you may supplicate in your own words and language — there are well-known duas the Prophet ﷺ and his companions are reported to have recited, and learning them adds structure and meaning to each rite.",
      "Entering Ihram: recite the Talbiyah repeatedly from the moment you enter the state of Ihram until you begin Tawaf: 'Labbayk Allahumma labbayk, labbayka la sharika laka labbayk...' ('Here I am, O Allah, here I am. Here I am, You have no partner, here I am...').",
      "During Tawaf: there is no fixed dua for each circuit — pilgrims commonly recite the dua between the Yemeni Corner and the Black Stone: 'Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar' ('Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire').",
      "During Sa'i: while walking between Safa and Marwah, pilgrims often recite Qur'anic verses and personal supplications freely — this is an excellent time for heartfelt, personal dua in your own language.",
      "After Halq/Taqsir: once the hair is cut or trimmed and Umrah is complete, it is customary to thank Allah and make dua for acceptance of the pilgrimage. Our Islamic Tools page has a Dua of the Day feature if you'd like to continue building a habit of daily supplication after you return home.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Spiritual",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 10,
    publishedAt: "2026-05-18",
    status: "published",
  },
  {
    id: "b4",
    slug: "choosing-the-right-umrah-agency",
    title: "How to Choose the Right Umrah Travel Agency in Sri Lanka",
    excerpt:
      "What to check before you commit — licensing, reviews, itinerary transparency, and red flags to avoid.",
    content: [
      "With dozens of travel agencies in Sri Lanka offering Umrah packages, choosing the right one can feel overwhelming. Here's a practical checklist to work through before you commit.",
      "Verify licensing first. A legitimate Umrah operator should be registered and able to show proof of their travel agency license and any relevant IATA or SLTDA registration. Gold Verified and Premium Partner badges on UmrahPackages.lk are only issued after this kind of vetting.",
      "Read the itinerary line by line. A trustworthy agency will clearly state hotel names (not just star ratings), distance from the Haram, flight routing and layovers, and exactly what's included versus what costs extra (visa fees, Ziyarah tours, meals).",
      "Ask about the on-ground team. Reputable agencies have a dedicated coordinator or guide (often a Maulavi) accompanying or based in Makkah and Madinah who can assist with logistics and religious guidance during your stay.",
      "Be cautious of prices that are dramatically below the market average — this is often a sign of hidden costs, downgraded hotels after booking, or, in rare cases, outright scams. Compare a handful of packages side by side on our Compare page before making a decision, and always confirm final details directly with the agency over WhatsApp or phone.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-04-10",
    status: "published",
  },
  {
    id: "b5",
    slug: "umrah-packing-list-for-women",
    title: "The Complete Umrah Packing List for Women",
    excerpt: "Modest, comfortable, and practical — everything Sri Lankan women should pack for Umrah.",
    content: [
      "Packing for Umrah as a woman is about balancing modesty, comfort, and practicality for long days of walking and standing. Here is a complete list to work from.",
      "Clothing: pack loose-fitting, non-see-through abayas or modest outfits in breathable fabrics — cotton blends handle the heat far better than synthetic materials. Bring at least one dedicated white or light-colored outfit that meets Ihram conditions if your madhab/family custom calls for it, plus a few headscarves in easy-to-tie styles.",
      "Footwear: comfortable, well broken-in walking shoes are non-negotiable — you'll easily walk 15,000+ steps a day between the hotel, the Haram, and Sa'i. Pack a lightweight pair of sandals for inside the mosque.",
      "Toiletries: unscented soap and wudhu-friendly products (scented items are discouraged in the state of Ihram), a small first-aid kit, and any personal medication clearly labeled with your name.",
      "Extras worth packing: a small prayer mat or mat cover for airport/layover prayers, a portable charger, a lightweight shawl for air-conditioned mosque halls, and a few zip-lock bags for damp or dusty items on the way home.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-03-02",
    status: "published",
  },
  {
    id: "b6",
    slug: "umrah-vs-hajj-whats-the-difference",
    title: "Umrah vs. Hajj: What's the Difference?",
    excerpt: "A clear, simple breakdown of how Umrah and Hajj differ in timing, rites, and obligation.",
    content: [
      "Umrah and Hajj are both pilgrimages to Makkah, and they share several rites, but they differ in timing, obligation, and scale. Understanding the difference helps first-time pilgrims plan the right journey for their circumstances.",
      "Timing: Hajj can only be performed during a specific window in the Islamic calendar — the 8th to 13th of Dhu al-Hijjah. Umrah, on the other hand, can be performed at any time of the year, which is why it's often called the 'minor pilgrimage.'",
      "Obligation: Hajj is one of the Five Pillars of Islam and is obligatory once in a lifetime for every Muslim who is physically and financially able. Umrah is highly recommended (sunnah mu'akkadah in most views) but not obligatory in the same way.",
      "Rites: Hajj includes all the rites of Umrah (Ihram, Tawaf, Sa'i) plus additional rites unique to it — standing at Arafah, staying overnight at Muzdalifah and Mina, and the symbolic stoning of the Jamarat. Umrah is a shorter set of rites that can typically be completed within a few hours.",
      "Scale: Hajj draws several million pilgrims within the same short window each year, making logistics and crowd management far more complex than Umrah, which spreads pilgrims across the entire year.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 5,
    publishedAt: "2026-02-14",
    status: "published",
  },
  {
    id: "b7",
    slug: "umrah-visa-requirements-2026",
    title: "Umrah Visa Requirements for Sri Lankan Pilgrims (2026 Update)",
    excerpt:
      "How the Umrah e-visa process works for Sri Lankan passport holders — documents, typical processing time, and what your agency handles for you.",
    content: [
      "Most Sri Lankan pilgrims travel to Saudi Arabia today on the Umrah e-visa, issued through Saudi Arabia's Nusuk platform specifically for religious travel — a separate track from Saudi's general tourist e-visa. In practice, you will rarely apply for it yourself: your travel agency submits the Nusuk application as part of your package, using the documents you provide them.",
      "The documents agencies typically ask for are a passport valid for at least six months beyond your travel dates, a recent passport-style photo, your confirmed Umrah booking (return flight and hotel), and your meningococcal ACYW vaccination certificate. Some agencies or, in individual cases, Saudi authorities may also ask to see recent bank statements as proof you can support yourself during the trip — requirements here are not fixed and can vary, so ask your agency exactly what they need from you when you book.",
      "Rules around women travelling without a male mahram have eased significantly in recent years compared to older Umrah visa policies, and organized group travel has made this more straightforward in practice. Even so, policies can vary by agency and individual circumstance, and views on the religious requirement itself differ between scholars — see our separate article on Umrah without a mahram, and always confirm both your agency's current policy and the religious guidance from your own Maulavi before finalizing plans.",
      "Once your documents are submitted, visa processing is usually completed within a matter of days, but it's worth applying as soon as you confirm your package rather than close to departure — processing can slow down during high-demand periods like the weeks before Ramadan.",
      "Saudi visa rules are updated periodically, so treat this article as a general orientation rather than the final word: always confirm the current requirements directly with your booked agency, and use our Umrah Visa Guide tool for a step-by-step walkthrough of the process.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-01",
    status: "published",
  },
  {
    id: "b8",
    slug: "umrah-cost-from-sri-lanka-price-breakdown",
    title: "How Much Does Umrah Cost from Sri Lanka? A Full Price Breakdown",
    excerpt:
      "What actually makes up an Umrah package price — and the extra costs pilgrims often forget to budget for.",
    content: [
      "“How much does Umrah cost?” is one of the first questions every Sri Lankan pilgrim asks, and the honest answer is: it depends heavily on season, hotel distance, flight class and group size. Rather than quote a single number that goes stale the moment prices move, browse current listings on our Umrah Cost in Sri Lanka page, which pulls live minimum, average and maximum prices straight from the packages currently listed by Sri Lankan agencies.",
      "A handful of factors move the price more than anything else: travelling during Ramadan or the weeks around Hajj season costs noticeably more than travelling in quieter months; a hotel a short walk from the Haram costs more than one requiring a shuttle; a direct or business-class flight costs more than a budget one-stop routing; and a smaller, more private group costs more per person than a larger fixed-departure group.",
      "A typical package price bundles together the Umrah visa and agency service fee, return flights, hotel nights split between Makkah and Madinah, and ground transport between the two cities. Some packages fold in a Ziyarah tour of historical sites; others sell it as an add-on, so read the inclusions list carefully rather than comparing sticker prices alone.",
      "Beyond the package price itself, budget separately for costs most pilgrims forget: airport departure taxes, a local SIM card or eSIM for data, meals beyond the breakfast most hotels include, shopping and gifts to bring home, and tips for group guides or porters. Our Umrah Budget Calculator tool walks through these line by line so you can build a realistic total before you commit.",
      "The fairest way to compare two packages is to line them up on duration, hotel distance band and inclusions first, and only then compare the price — a cheaper package with a distant hotel and no Ziyarah isn't necessarily better value than a slightly pricier one that includes both.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-08-22",
    status: "published",
  },
  {
    id: "b9",
    slug: "how-many-days-do-you-need-for-umrah",
    title: "How Many Days Do You Need for Umrah? A Trip-Length Planning Guide",
    excerpt: "From a quick 5-day trip to a relaxed two-week pilgrimage — how to choose the right length for you.",
    content: [
      "Umrah itself — the rites of Ihram, Tawaf, Sa'i and Halq/Taqsir — can be completed in a matter of hours once you're at the Haram. The question of how many days to spend in Saudi Arabia is really about everything around those rites: travel time, rest, additional worship, and how much of Makkah and Madinah you want to see.",
      "At the shorter end, some pilgrims manage a trip of around five to seven days: enough time to perform Umrah, spend a few days in prayer and reflection at both holy mosques, and fit in a short Ziyarah, but with little room for delays or rest days. This works best for pilgrims with travelled before and know what to expect, or who have limited leave from work.",
      "A more common and comfortable range for Sri Lankan pilgrims is ten to fourteen days: a few days settling in and worshipping in Makkah, time in Madinah for prayers at Masjid an-Nabawi and a proper Ziyarah of the historical sites, and enough slack in the schedule to rest, especially in the summer heat.",
      "Trip length also depends on who's travelling. Families with young children or elderly parents often do better with a longer, less rushed itinerary that allows for slower pacing — see our guides on Umrah with children and Umrah for elderly pilgrims for specifics. During Ramadan, especially the last ten nights, availability for longer stays is tighter and in higher demand, so book earlier than you think you need to.",
      "When you're comparing packages on UmrahPackages.lk, use the duration shown on each listing alongside the departure dates to find a trip length that matches your leave, budget and the pace you want — there's no single right answer, only the one that fits your circumstances.",
    ],
    coverImageUrl: BLOG_COVERS.lantern,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-25",
    status: "published",
  },
  {
    id: "b10",
    slug: "can-a-woman-perform-umrah-without-a-mahram",
    title: "Can a Woman Perform Umrah Without a Mahram? What Sri Lankan Pilgrims Should Know",
    excerpt:
      "A general overview of the mahram question for women travelling for Umrah — and why this is a question for your own scholar, not a travel website.",
    content: [
      "This is one of the most commonly searched Umrah questions among Sri Lankan pilgrims, and it sits at the intersection of two different things: what Saudi Arabia's entry rules currently allow, and what Islamic scholarship says a woman should do. This article covers the first in general terms; it is not a religious ruling on the second.",
      "On the practical side, Saudi Arabia's visa and entry policies for women travelling for Umrah have eased substantially compared to older rules, and organized group travel — where a woman travels as part of a supervised tour group rather than alone — has made independent travel more workable in practice for many pilgrims. That said, exact policies can vary by circumstance, and it's worth confirming your specific situation with your travel agency before you book.",
      "On the religious side, scholarly views on whether a woman requires a mahram (a close male relative) to travel for Hajj or Umrah differ, including between different schools of thought, and the details matter — distance travelled, whether she is travelling with a trustworthy group of other women, age, and individual circumstances can all affect the answer given. This is exactly the kind of question that deserves a considered answer from a qualified source, not a generic one from a travel platform.",
      "Practically, many Sri Lankan agencies address this by grouping women travellers together for flights, transfers and shared accommodation within the wider group, and by assigning a group leader or Maulavi who coordinates on-ground logistics. If you're planning to travel without a mahram, ask your agency directly how they handle this before you book — see our guide on choosing the right Umrah agency for what else to check.",
      "This article is presented in general terms and is not affiliated with, or speaking on behalf of, any particular school of thought, sect or organization. For a ruling specific to your own situation, please consult your Maulavi or a qualified religious scholar you trust before making travel decisions on this basis.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Spiritual",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-08-27",
    status: "published",
  },
  {
    id: "b11",
    slug: "economy-vs-luxury-umrah-packages",
    title: "Economy vs. Luxury Umrah Packages: What Actually Changes",
    excerpt: "The rites of Umrah don't change with price — here's exactly what does.",
    content: [
      "Every Umrah package, whatever its price, gives you access to the same rites: the same Ihram, the same Tawaf around the Kaaba, the same Sa'i between Safa and Marwah. What changes as the price goes up isn't the pilgrimage itself, but the comfort and convenience around it.",
      "Economy and standard packages typically mean hotels set further back from the Haram (often relying on a shuttle rather than a short walk), rooms shared between three or four pilgrims, larger tour groups moving on a fixed shared schedule, and economy-class flights, often with a layover. This is where most first-time, budget-conscious Sri Lankan pilgrims start, and it delivers a complete, valid Umrah experience.",
      "Premium and luxury packages shift the comfort dial: hotels directly facing or a short walk from the Haram, double or single room occupancy instead of shared rooms, smaller groups or private transport, more flexibility to set your own pace between prayers, and sometimes business-class flights. None of this is required for a valid Umrah — it's purely about physical comfort and time saved walking or waiting.",
      "So how do you decide? If you're travelling with elderly parents or young children, or if this is a once-in-a-lifetime trip where minimizing walking and fatigue matters, paying for a hotel closer to the Haram is often worth it — see our guides on Umrah for elderly pilgrims and Umrah with children. If you're young, fit and comfortable walking twenty minutes each way, an economy package gets you the same spiritual outcome for meaningfully less money.",
      "Browse our cheap Umrah packages and luxury Umrah packages pages side by side to see exactly how hotel distance, inclusions and price move together across current Sri Lankan agency listings.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-29",
    status: "published",
  },
  {
    id: "b12",
    slug: "flights-colombo-to-saudi-arabia-for-umrah",
    title: "Flights from Colombo to Saudi Arabia for Umrah: Airlines and Routes Explained",
    excerpt: "Direct SriLankan Airlines flights, one-stop Gulf routings, and which Saudi airport to fly into.",
    content: [
      "SriLankan Airlines operates flights from Colombo directly to Jeddah, and at times to Madinah during peak Umrah and Hajj periods, making it the most straightforward option for pilgrims who prefer to avoid a layover. Most agency packages that include flights will book through SriLankan Airlines or a similarly direct option where schedules allow.",
      "One-stop routings through major Gulf hubs are common too, and can sometimes work out cheaper or fit your dates better: flydubai or Emirates via Dubai, Qatar Airways via Doha, Oman Air via Muscat, and Etihad via Abu Dhabi all connect on to Jeddah or Madinah. If you're booking flights independently of a package, comparing a few of these routings on a flight search site is worth the extra few minutes.",
      "Which airport you fly into matters for your itinerary: Jeddah's King Abdulaziz International Airport is the standard entry point and sits roughly one and a half to two hours by road from Makkah, making it the natural choice if your trip starts with Umrah rites first. Prince Mohammad bin Abdulaziz Airport in Madinah is the better entry point if your agency's itinerary starts in Madinah instead. Most Sri Lankan group packages fly into Jeddah, perform Umrah in Makkah, then travel overland to Madinah before flying home from either city.",
      "Fares and schedules shift noticeably around Ramadan and Hajj season as demand spikes, so if you're arranging flights yourself rather than through a bundled package, book earlier than you would for an ordinary holiday and keep an eye on schedule changes in the weeks leading up to departure.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-08-30",
    status: "published",
  },
  {
    id: "b13",
    slug: "umrah-health-vaccination-requirements",
    title: "Umrah Health and Vaccination Requirements for Sri Lankan Pilgrims",
    excerpt: "The meningitis vaccine timing rule, and the other jabs worth getting before you travel.",
    content: [
      "Saudi Arabia requires all Umrah and Hajj pilgrims aged one year and older to hold a valid meningococcal ACYW vaccination certificate. Timing matters here: the certificate needs to be issued no fewer than ten days before you arrive in Saudi Arabia, and it remains valid for up to three years for the polysaccharide vaccine or five years for the conjugate vaccine, depending on which one you receive. Plan this appointment as one of the first things you do once your travel dates are confirmed, not something to squeeze in the week before you fly.",
      "COVID-19 vaccination or testing requirements for entry have changed repeatedly since 2020 and may be updated again, so check the current rule with your travel agency or the Saudi embassy shortly before departure rather than relying on what was required last year or on what a friend was told.",
      "Beyond what's mandatory, health authorities commonly recommend a seasonal influenza vaccine given how crowded the Haramain get, a polio booster if you haven't had one as an adult, a pneumococcal vaccine for pilgrims aged 65 and above, and general travel vaccines like hepatitis A and B. None of these are unique to Umrah, but the crowded, close-contact nature of the pilgrimage makes them worth discussing with your doctor or a travel clinic.",
      "Health preparation for Umrah isn't only about vaccines. Makkah and Madinah are extremely hot outside the winter months, so pilgrims — especially elderly travellers — should prioritise hydration, sun protection and comfortable, broken-in footwear just as seriously as any injection. Our Makkah & Madinah Weather tool and our guide for elderly pilgrims cover this in more detail.",
      "Because health entry rules are reviewed periodically by Saudi authorities, treat this article as a starting point and confirm the exact current requirements with your agency or the Saudi Ministry of Health close to your departure date.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-01",
    status: "published",
  },
  {
    id: "b14",
    slug: "whats-included-in-an-umrah-package",
    title: "What's Included in an Umrah Package? A Line-by-Line Guide",
    excerpt: "Reading a package listing properly — what's usually bundled in, and what almost always costs extra.",
    content: [
      "Most Umrah packages from Sri Lankan agencies bundle together the same core elements: return flights, the Umrah visa and its processing, hotel accommodation split between Makkah and Madinah, and ground transport between the two cities, often with an orientation briefing on arrival. Beyond that core, exactly what's included starts to vary a lot from one agency to the next.",
      "Commonly excluded, or sold as an optional add-on: a guided Ziyarah tour of historical sites in and around Makkah and Madinah, meals beyond breakfast (most hotels include breakfast, fewer include lunch or dinner), personal expenses like shopping and laundry, tips for group guides or porters, and travel insurance, which is worth adding even when it isn't required for your visa.",
      "The details that matter most when comparing two listings side by side are the hotel names (not just the star rating), how far each hotel actually is from the Haram, whether rooms are shared (quad or triple) or private (double or single), the specific departure and return dates, and the airline and any layovers. Every package listed on UmrahPackages.lk includes these details precisely so pilgrims can compare like-for-like rather than guessing from a headline price.",
      "Before paying any deposit, ask the agency directly — WhatsApp is fine — to confirm in writing exactly what's included and excluded for your specific package. A short question at this stage can prevent an expensive surprise once you're already in Makkah. Our Umrah Budget Calculator and Umrah Visa Guide tools are useful companions for working out what else to plan and budget for beyond the package price itself.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-02",
    status: "published",
  },
  {
    id: "b15",
    slug: "group-family-or-individual-umrah-package",
    title: "Group, Family or Individual Umrah Package: Which Is Right for You?",
    excerpt: "How the three common package formats differ, and how to choose based on who you're travelling with.",
    content: [
      "Group packages are the most common format offered by Sri Lankan agencies: pilgrims travel together on a fixed itinerary and shared schedule, usually with an agency guide or Maulavi coordinating the group throughout. They tend to be the most affordable per person, and the shared structure works well for first-time pilgrims who want a clear schedule and the company of fellow travellers.",
      "Family-oriented packages are built around a family unit rather than a mixed group — think parents travelling with children, or with elderly relatives — with room configurations and pacing adjusted accordingly. These suit families who want more privacy than a large group setup, or who need the flexibility to slow down for a child or an older relative; see our guides on Umrah with children and Umrah for elderly pilgrims for what to look for.",
      "Individual or private packages sit at the other end: private transport, a schedule you set yourself rather than a fixed group itinerary, and the freedom to spend as much or as little time as you like on Ziyarah and personal worship. These come at a higher price point and suit pilgrims who value flexibility over structure, or who are combining Umrah with other personal travel plans.",
      "Worth knowing: most current Sri Lankan agency listings on our platform are organized as group packages, since that's the format most local operators run by default. If you specifically need a family-configured package, use the filters on our Packages page, browse our Family Umrah Packages page, or simply ask an agency directly whether they can arrange a custom family itinerary — many will, even if it isn't their standard listed product.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-03",
    status: "published",
  },
  {
    id: "b16",
    slug: "managing-money-on-umrah-currency-and-budgeting",
    title: "Managing Money on Umrah: Currency, Cash and Budgeting Tips for Sri Lankan Pilgrims",
    excerpt: "What currency to carry, cash vs. cards in Makkah and Madinah, and how to budget for the extras.",
    content: [
      "The Saudi Riyal (SAR) is the standard currency across Makkah and Madinah. While a few vendors near the Haram will informally accept US Dollars or even Sri Lankan Rupees, the exchange rate you'll get is rarely in your favour — it's best to convert to SAR before you travel or shortly after you land.",
      "Exchange rates between the Sri Lankan Rupee and the Saudi Riyal move daily, so rather than plan around a fixed number, compare rates at a couple of licensed money changers in Colombo before you leave, and check a live currency converter — our Islamic Tools section has one — close to your actual travel date so your budget reflects the real rate, not an outdated one.",
      "Cards are increasingly accepted at hotels, larger shops and taxis in both cities, but cash SAR remains essential for smaller vendors, local transport, tipping group guides or porters, and the many small stalls around the Haram. A sensible approach is to carry a mix of both, and to keep a small emergency cash reserve separate from your main wallet in case a card is declined or a machine is out of service.",
      "Beyond the package price, set yourself a daily spending allowance for meals, shopping and any Ziyarah extras, and track it as you go — a small notebook or a notes app on your phone works fine. Keeping a modest reserve on top of that budget covers the unexpected: an extra taxi, a missed hotel meal, or medication you didn't plan for. Our Umrah Budget Calculator tool can help you set this allowance realistically before you fly.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-04",
    status: "published",
  },
  {
    id: "b17",
    slug: "umrah-packing-checklist-men",
    title: "What to Pack for Umrah: A Men's Checklist",
    excerpt:
      "The Ihram-specific items, footwear, and practical extras Sri Lankan men often forget to pack before their Umrah journey.",
    content: [
      "Packing for Umrah as a man comes with one requirement that makes it genuinely different from packing for any other trip: the Ihram. Once a pilgrim enters the state of Ihram at or before the Miqat, men are required to wear two pieces of plain, unstitched white cloth — one wrapped around the lower body (the izar) and one draped over the shoulders and upper body (the rida). No sewn or tailored garments, no pockets, no buttons. If you've already read our packing list guide for women, you'll notice the two lists diverge sharply here, since this restriction applies specifically to men. It's worth buying your Ihram cloth a few weeks before departure and practicing wrapping and securing it at home, rather than figuring it out for the first time at the airport or Miqat.",
      "Most experienced travellers recommend packing at least two full sets of Ihram cloth rather than one. Saudi Arabia's climate, especially around the Haram in Makkah, can be hot, and a spare set means you're not stuck rewearing a sweat-soaked cloth or scrambling to find a replacement mid-trip. Since Ihram garments have no pockets, an Ihram belt — a simple fabric pouch that ties around the waist — is genuinely useful for carrying your passport, phone, room key, and cash without needing to pin anything to the cloth itself. A handful of large, blunt safety pins are still worth packing, since many pilgrims use them to keep the shoulder cloth from slipping, even though nothing should actually be stitched into the fabric.",
      "Footwear is where a lot of first-time pilgrims get caught out. While in the state of Ihram, men are expected to wear open sandals or simple rubber slippers that leave the top of the foot exposed, typically with a strap that sits between the big toe and the second toe rather than a closed design covering the ankle or heel. Regular covered shoes, trainers, or anything that encloses the foot don't fit this requirement during Ihram. Pack a sturdy, comfortable pair of these sandals — cushioned ones matter more than you'd expect once you're walking long distances on marble floors — and bring a second pair as backup, since straps do break under heavy daily use.",
      "Toiletries need a second look too. Once in Ihram, scented soaps, perfumed shampoos, and cologne are generally to be avoided, so it helps to pack a small, unscented soap or shower gel specifically for that period, along with an unscented sunscreen if you burn easily. Exactly when scent restrictions begin and end can vary slightly depending on the school of thought you follow, so it's worth asking your own Maulavi for clarity rather than relying on general guidance alone. Outside of Ihram — during flights, hotel stays, and the days between rituals — pack normal modest clothing: a few loose shirts or thobes, comfortable walking shoes, and a light jacket if you're travelling during cooler months, since mosque interiors and flights are often air-conditioned.",
      "Beyond clothing, a few practical extras make the trip smoother: a compact backpack for daily essentials at the Haram, a power bank for your phone, a printed copy of your visa and hotel booking, and a small pouch for loose change and coins, which come in handy for small purchases and donations. If you're travelling as part of a family, it's worth reading alongside this our guide on Umrah with an infant or newborn and our packing list for women, so the household is packing as one unit rather than duplicating or missing items. And if budgeting for extras like a second Ihram set or better sandals feels tight, our Umrah Budget Calculator tool can help you see where that spending fits against flights, accommodation, and the rest of your package.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-05",
    status: "published",
  },
  {
    id: "b18",
    slug: "umrah-visa-application-process-sri-lanka",
    title: "How to Apply for an Umrah Visa from Sri Lanka: The Step-by-Step Process",
    excerpt:
      "The actual step-by-step process Sri Lankan pilgrims go through to get an Umrah visa issued, from application to approval.",
    content: [
      "Once you know you're eligible for an Umrah visa — which we cover separately in our Umrah visa requirements guide — the next question is simply: how does a Sri Lankan pilgrim actually get one issued? In practice, almost nobody applies for an Umrah visa entirely on their own. Saudi Arabia's Umrah visa system runs through an official digital platform, generally referred to as Nusuk, which licensed travel and Umrah agencies use to submit and process visa applications on behalf of pilgrims. If you've booked a package through an agency listed on UmrahPackages.lk, that agency (or their designated visa handling partner) is typically the one submitting your application into this system rather than you logging in and doing it yourself.",
      "What you're actually responsible for is supplying accurate, complete information and documents to your agency early. This usually means your passport (valid well beyond your travel dates), a recent passport-style photograph that meets standard visa photo rules — plain light background, no glasses, no headwear except for religious purposes where the face remains fully visible, and taken within the last few months — along with basic personal and travel details, and for women under a certain age, mahram or guardianship documentation, which we go into in more depth in our mahram requirements guide. Agencies will usually give you a checklist of exactly what they need; the most common cause of delay is pilgrims sending in a blurry scan, an expired passport, or a photo that doesn't meet the format required.",
      "Once your documents are submitted, processing timeframes can vary depending on the season, how close you are to peak travel periods like school holidays or the months around Ramadan, and how quickly your agency processes paperwork internally. It's realistic to expect anywhere from a few days to a couple of weeks for a visa to be issued once everything is correctly submitted, though this is not a fixed number and can shift year to year. Because of this, most agencies advise submitting your documents well ahead of your intended travel date rather than waiting until the last few weeks, especially if you're travelling during a busier period.",
      "It also helps to understand what an Umrah visa actually looks like once issued: for most pilgrims today, it exists as an electronic visa linked to your passport rather than a physical stamp or sticker, and your agency or the platform used will typically share confirmation with you or provide something to print and carry as a reference. Keep a digital and printed copy of any visa confirmation, your flight tickets, and your hotel booking together in one folder, since immigration and airline check-in staff may ask to see them together.",
      "If anything about your specific situation feels unclear — a name mismatch between documents, a previous visa history with Saudi Arabia, or travelling with a child on a separate passport — it's worth raising it directly with your chosen agency before booking rather than after, since they're the ones who will actually be submitting your case. Comparing a few agencies side by side on how clearly they explain their visa process is one of the simpler ways to gauge how organised they are, and it pairs well with the advice in our guide on choosing the right agency.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-06",
    status: "published",
  },
  {
    id: "b19",
    slug: "common-mistakes-first-time-umrah-pilgrims",
    title: "Common Mistakes First-Time Pilgrims Make During Umrah (and How to Avoid Them)",
    excerpt:
      "The practical, logistical slip-ups that catch first-time pilgrims off guard in Makkah and Madinah, and simple ways to avoid them.",
    content: [
      "One of the most common mistakes first-time pilgrims make happens before Umrah even officially begins: misunderstanding when Ihram restrictions actually take effect. Many travellers assume they can change into Ihram cloth casually at the hotel or airport in Jeddah, when in fact the intention (niyyah) and the restrictions of Ihram are meant to begin at or before the designated Miqat point — the boundary a pilgrim crosses on the way to Makkah. If you're flying in and your flight path or route means you'll cross this boundary in the air, your agency should brief you in advance so you're not caught off guard trying to figure it out mid-journey. Because the exact timing and boundary can depend on your specific route, it's worth confirming the details with your agency's group leader and your own Maulavi ahead of the trip rather than assuming.",
      "Once inside the Haram, a very common mistake is rushing through Tawaf — trying to complete the seven circuits of the Kaaba as fast as possible, often by pushing through crowds or cutting inner rows. This tends to backfire: it raises the risk of getting separated from your group, causes unnecessary physical strain, and can turn a moment meant for reflection into a stressful scramble. Pilgrims who pace themselves, especially older travellers or those doing Tawaf for the first time, generally have a calmer and safer experience, even if it takes longer.",
      "Dehydration is another issue that catches people off guard, particularly given how warm Makkah and Madinah can get. Between the physical activity of Tawaf and Sa'i and the dry climate, it's easy to underestimate how much water you need, especially since the free Zamzam water available throughout the Haram makes it easy to assume you're drinking enough when you're not. Carrying a small refillable bottle and drinking on a schedule rather than only when thirsty is a simple habit that prevents a lot of avoidable fatigue and headaches.",
      "On the practical side, overpacking is a recurring complaint among returning pilgrims — bringing far more clothing and belongings than needed, only to struggle with luggage weight limits and cramped hotel rooms. A related and often bigger issue is not checking how far the hotel actually is from the Haram before booking. Listings can describe a hotel as 'near' the Haram in ways that don't match the actual walking distance, especially for elderly travellers or those with mobility concerns, so it's worth asking your agency for a specific distance in metres or an estimated walking time rather than relying on general descriptions — our guide on what's included in a package touches on how accommodation details are usually listed.",
      "Finally, losing track of group meeting points is one of the most stressful — and most preventable — mistakes pilgrims make, particularly inside the vast, crowded complex of the Haram where phone signal can be unreliable. Before entering for any ritual, agree on a specific, memorable meeting point with your group or family (a particular gate number is usually more reliable than a vague landmark), and consider keeping a card with your hotel's name and address on you in case you do get separated. Small habits like these do more to protect a first-time pilgrim's experience than almost anything else on this list.",
    ],
    coverImageUrl: BLOG_COVERS.compass,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-07",
    status: "published",
  },
  {
    id: "b20",
    slug: "direct-vs-layover-flights-colombo-umrah",
    title: "Direct vs Layover Flights from Colombo for Umrah: What's the Real Difference?",
    excerpt:
      "Weighing total travel time, cost, and jet lag when choosing between a direct flight and a layover route from Colombo.",
    content: [
      "For Sri Lankan pilgrims booking flights to Saudi Arabia, the choice usually comes down to two options: a direct flight where one exists, or a layover route connecting through a hub airport. SriLankan Airlines has, at various points, operated direct services between Colombo and Jeddah, though route availability on any given airline can change from season to season based on demand and operational decisions. Because of this, it's worth checking current schedules directly with the airline or your agency at the time of booking rather than assuming a direct route is guaranteed to be running, and our guide on flights from Colombo to Saudi Arabia is a good place to start that comparison.",
      "When a direct flight is available, the appeal is straightforward: a single takeoff and landing, no risk of a missed connection, and generally a shorter total door-to-door travel time. This matters more than it might seem for Umrah specifically, since many pilgrims travel in family groups with elderly parents or young children, and fewer transit points mean less physical strain, less luggage handling, and fewer opportunities for something to go wrong logistically.",
      "Layover routes, typically connecting through major Gulf hub airports on carriers that serve those hubs, are the more commonly available option and often come at a lower fare, which is a big part of why many packages are built around them. The trade-off is added total journey time — sometimes several extra hours once you account for the layover itself — plus the physical toll of an additional airport transit, security screening, and potentially a terminal change. For pilgrims planning to enter Ihram partway through the journey, a layover route also means being clear in advance about exactly where and when the Miqat boundary applies to that specific routing, which your agency should be able to walk you through.",
      "On jet lag and fatigue specifically, the honest answer is that neither option eliminates it, but a direct flight generally reduces overall fatigue simply by cutting total travel time and avoiding a second cramped landing and takeoff. If you do book a layover route, a longer layover (rather than a very tight connection) can actually work in your favour, giving you a chance to stretch, eat properly, and rest before continuing, rather than rushing between gates while exhausted. Booking an overnight layover with a short hotel rest, where schedules allow it, is something some pilgrims choose specifically to arrive in Saudi Arabia in better shape for the physical demands of Umrah.",
      "Ultimately, the right choice depends on your budget, how much total travel time you're comfortable with, and who you're travelling with. A young, fit solo traveller might happily trade a longer layover for a meaningfully cheaper fare, while a family travelling with elderly parents may find a direct or minimal-layover route worth the extra cost simply for the reduced strain. Comparing a few packages side by side on our platform, with attention to the specific routing and layover length each one includes, is the most reliable way to see what trade-off you're actually being offered rather than judging by price alone.",
    ],
    coverImageUrl: BLOG_COVERS.lantern,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 6,
    publishedAt: "2026-09-08",
    status: "published",
  },
  {
    id: "b21",
    slug: "umrah-with-infant-newborn-sri-lankan-parents",
    title: "Umrah with an Infant or Newborn: What Sri Lankan Parents Should Know",
    excerpt:
      "What Sri Lankan parents should actually plan for when bringing an infant or newborn along on Umrah.",
    content: [
      "A question that comes up often among Sri Lankan families planning Umrah with a very young baby is whether an infant needs to be dressed in Ihram at all. The general understanding across Islamic scholarship is that an infant is not held to the same ritual obligations as an adult, since the obligations of Ihram are tied to a level of maturity and responsibility a newborn simply hasn't reached. That said, many parents still choose to dress their baby in simple, similar white garments out of custom and to keep the experience visually consistent with the rest of the family, even though the actual rites and restrictions are really being observed by the adult carrying the child. Because views and practices can differ slightly here, it's worth asking your own Maulavi for guidance specific to your situation rather than assuming one approach is universally agreed upon.",
      "Airline policy is one of the more practical things to sort out early. Most airlines flying from Colombo require infants to be under a certain age (commonly around two years old) to travel as a lap infant at a reduced fare, and typically ask for the baby's birth certificate or passport at booking and check-in. Bassinet availability on longer flights is usually limited and allocated on a request basis, so it's worth contacting the airline or your agency as early as possible if you'd like one, rather than assuming it will be available on the day.",
      "Health and vaccination considerations deserve early attention too, ideally a few weeks before travel. Saudi Arabia's entry health requirements can include specific vaccination expectations for travellers, including for infants, and these have been known to change, so checking current requirements with a paediatrician or travel clinic — alongside the general guidance in our health and vaccination requirements guide — is safer than relying on what was required in a previous year. It's also worth discussing with your paediatrician whether your baby is fit to travel at all given their age and any health conditions, particularly for a newborn in the first few weeks of life.",
      "Packing for an infant on Umrah is less about religious requirements and more about the basics of travelling with a baby in a hot climate and crowded spaces: enough diapers and wipes to cover delays, a lightweight and easily foldable stroller or a sturdy baby carrier for navigating the Haram's crowds, sun protection, and any formula or feeding equipment you rely on, since availability of specific brands in Saudi Arabia isn't something to count on. A small, well-stocked baby bag that one parent can carry hands-free through Tawaf and Sa'i tends to matter more on the day than almost anything else on the packing list.",
      "Logistically, most families find that performing Tawaf and Sa'i with an infant works best when one adult carries the baby throughout while another handles bags and water, and taking turns if the rituals run long. Crowded periods of the day can be genuinely difficult with a baby, so many parents planning around a newborn choose quieter hours where possible and build extra rest time into the itinerary rather than trying to match the pace of a group without children. If you're travelling as a wider family, it's worth reading this alongside our packing list for women and our men's Umrah packing checklist so the whole family's preparation is planned together rather than piecemeal.",
    ],
    coverImageUrl: BLOG_COVERS.suitcase,
    category: "Family",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-09",
    status: "published",
  },
  {
    id: "b22",
    slug: "umrah-on-tourist-visa-combine-with-holiday",
    title: "Umrah on a Tourist Visa: Can You Combine Umrah with a Holiday in Saudi Arabia?",
    excerpt:
      "Whether a Saudi tourist visa currently lets you perform Umrah has shifted more than once in recent years — here's how to check before you book.",
    content: [
      "It's a question we hear often from Sri Lankan travellers planning a trip to Saudi Arabia: if you're already going for a holiday, or you happen to hold a Saudi tourist visa for another reason entirely, can you simply perform Umrah while you're there instead of applying for a separate, dedicated Umrah visa? It sounds like it should have a simple yes-or-no answer, and for a while it more or less did. But the honest answer today is that this depends on rules that have genuinely shifted more than once in recent years, and getting it wrong on the day can mean being turned away at the Miqat, or running into problems with immigration that could have been avoided with a five-minute phone call to your agency beforehand. This is one of those topics where we'd rather be genuinely useful than falsely confident — pointing you toward how to check the current position for yourself, rather than handing you a rule that may already be outdated by the time you actually book your flights and finalise your itinerary.",
      "For a long time, performing Umrah in Saudi Arabia required its own specific Umrah visa, issued through a licensed operator and tied directly to the pilgrimage rather than to general travel or tourism. Over the past several years, though, Saudi authorities have moved in a noticeably more open direction, at various points allowing holders of tourist visas — and in some cases other visa categories too — to also perform Umrah outside the Hajj season, as part of a wider strategy to grow both religious and general tourism side by side under the country's broader Vision 2030 push. For travellers who wanted to see more of the country — Riyadh, AlUla, the Red Sea coast, Jeddah's old town — alongside their spiritual journey, this genuinely opened up options that simply didn't exist a decade ago, and it's a large part of why this exact question comes up so often from pilgrims planning ahead.",
      "That said, these rules have not stood still, and treating any single year's policy as a fixed, permanent fact would be a mistake worth avoiding. Saudi authorities have periodically tightened documentation and eligibility requirements around Umrah travel, particularly in the lead-up to and during Hajj season, largely to manage overcrowding at the holy sites and to prevent people from using a tourist or Umrah entry to attempt Hajj itself without the required, separately-issued Hajj permit. What was permitted for a given nationality in one season is not guaranteed to remain exactly the same the next, hotel pre-booking and other documentation requirements have also been introduced and adjusted over time, and the specifics can differ depending on your passport — so a general rule you've read about online may not map cleanly onto your situation as a Sri Lankan traveller booking today.",
      "Because of that, our strongest and most practical advice is simple: don't plan your entire trip around what a friend, a forum post, or even an older article — including one of ours, should the details ever change after publishing — says was allowed last year. Confirm the current position directly with a licensed Umrah agency, or check the official Nusuk platform, before you finalise flights or accommodation around the idea of combining a tourist visa with Umrah. Our guide on Umrah visa requirements is a solid starting point for understanding the general visa landscape and the kinds of documents typically involved in any Umrah trip, but for this specific question of combining a holiday and Umrah on one visa, treat it as something to verify at the point of booking rather than something to assume in advance based on what used to be true.",
      "If flexibility to explore beyond Makkah and Madinah is genuinely what's drawing you to this idea in the first place, it's also worth weighing whether a structured Umrah package might actually serve you better than a self-planned combination trip, even in seasons where a tourist-visa route is technically available to you. A dedicated package tends to bundle accommodation, ground transport, and ziyarat visits to historical sites in a way that a do-it-yourself itinerary often doesn't manage as smoothly, particularly for first-time travellers who are also trying to navigate an unfamiliar country's visa rules for the very first time, all while managing prayer times, Ihram, and jet lag. Our guide on individual and family packages can help you weigh that more structured option against the appeal of planning everything yourself.",
    ],
    coverImageUrl: BLOG_COVERS.calendar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-10",
    status: "published",
  },
  {
    id: "b23",
    slug: "meaning-of-talbiyah-when-to-recite-and-stop",
    title: "The Meaning of Talbiyah: When to Recite It and When to Stop",
    excerpt:
      "What the Talbiyah means, when you begin reciting it at the Miqat, and the point in Tawaf where pilgrims traditionally fall silent.",
    content: [
      "If there's one phrase that defines the sound of Umrah more than any other, it's the Talbiyah. From the moment pilgrims enter the state of Ihram, the words \"Labbayk Allahumma Labbayk, Labbayka la sharika laka Labbayk\" ring out across airport terminals, coach buses, and the roads leading into Makkah, recited by pilgrims of every background, language, and nationality, all in the same Arabic wording regardless of where they've travelled from or what language they otherwise pray in. It's repeated by millions of people every single year, and for many first-time pilgrims from Sri Lanka, it's often the exact moment the emotional weight of the journey finally sinks in — the point where the trip stops feeling like travel logistics and starts feeling, unmistakably, like worship.",
      "The meaning, broadly translated, runs something like: \"Here I am, O Allah, here I am. Here I am, You have no partner, here I am. Indeed all praise, blessing, and sovereignty belong to You. You have no partner.\" It's structured as a response — a pilgrim answering a call, presenting themselves in humility and readiness, having stripped away the usual markers of wealth, status, occupation, and background in favour of the plain, simple garments of Ihram that every pilgrim wears alike. Many pilgrims describe that reciting it over and over, rather than just once at the very start of the journey, is what gradually turns it from memorised words learned in childhood into something that feels like a genuinely personal declaration of presence, humility, and intent made in that moment.",
      "The Talbiyah begins the moment a pilgrim enters the state of Ihram — that is, after making the intention (niyyah) for Umrah, generally at or before crossing the designated Miqat boundary on the way toward Makkah. From that point onward, it's recited frequently throughout the rest of the journey: in the car or coach, while walking, in between other supplications and quiet moments of personal reflection, essentially whenever it comes to mind rather than at fixed, scheduled intervals. Men are generally encouraged to recite it audibly, raising their voice where the setting appropriately allows it, while women typically recite it more quietly to themselves — though both are simply expressing the exact same words, meaning, and underlying intention regardless of volume.",
      "As Makkah draws closer and the Haram finally comes into view for the first time, many pilgrims notice their recitation naturally becoming quieter, slower, and more reflective, shifting gradually from an outward declaration into something closer to inner readiness and quiet anticipation of what's ahead. The generally understood point at which pilgrims stop reciting the Talbiyah altogether is when they begin Tawaf — that is, once they actually start the seven circuits around the Kaaba itself, having entered the mosque and approached the starting point. Right up until that exact moment, it's considered good practice to keep repeating it as often, and as sincerely, as possible, rather than saving it only for certain stretches of the overall journey.",
      "As with several points of ritual timing during Umrah, there are minor differences of view among scholars on the exact transition points around the Talbiyah and precisely when it should taper off, so if you'd like to be fully precise about the timing as you approach the Haram, it's worth asking your own Maulavi before you travel rather than relying solely on general guidance like this one for something this specific to your own practice. Pairing that conversation with our Umrah dua guide can help you feel properly prepared for the fuller sequence of recitations and supplications that follow once Tawaf actually begins and continues through the rest of your Umrah.",
    ],
    coverImageUrl: BLOG_COVERS.tasbih,
    category: "Rituals",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-09-11",
    status: "published",
  },
  {
    id: "b24",
    slug: "umrah-badal-on-behalf-of-deceased-relative",
    title: "Can You Perform Umrah on Behalf of a Deceased Relative? (Umrah Badal)",
    excerpt:
      "What Umrah Badal means in general terms — and why the specific conditions for performing it should always be confirmed with your own Maulavi.",
    content: [
      "It's a question that comes up more often than you might expect, usually from someone who has just lost a parent, or whose elderly relative can no longer travel because of age or declining health: can I perform Umrah on their behalf? The concept people are usually referring to is known as Umrah Badal — badal meaning roughly \"in place of\" or \"substitute\" — and it's a widely recognised idea that a good number of Sri Lankan pilgrims ask their agencies, and more importantly their local mosque or Maulavi, about long before they ever get as far as booking flights or a package. If this question has been sitting with you since a loss in your own family, you're certainly not the first person to wonder about it, and you won't be the last.",
      "In general terms, the broader idea behind Badal Umrah, and Badal Hajj alongside it, is that certain acts of pilgrimage can, in some circumstances, be carried out by one person acting on behalf of another person who has passed away, or who is alive but physically unable to undertake the journey themselves due to age, illness, or disability. It's a concept that many pilgrims find genuinely comforting, especially when a parent or grandparent had long spoken of wanting to perform Umrah themselves but never got the chance before they passed away, or became too frail or unwell to make the journey within their own lifetime. For many families, it offers a meaningful way to still fulfil something that clearly mattered a great deal to someone they loved and lost.",
      "Here's the part we want to be genuinely clear about: the specific conditions attached to Umrah Badal — including exactly who is eligible to perform it on someone else's behalf, whether that person must have already completed their own personal Umrah first, what intention and wording is required at the time, and the precise circumstances under which it's considered to properly apply at all — are matters of detailed scholarly discussion, and views can differ meaningfully depending on school of thought and individual family circumstance. This is simply not something we're in any position to give you a definitive religious ruling on through a travel comparison website, and honestly, no travel website genuinely should try to, no matter how confidently it's written.",
      "Because of that, our firm and repeated recommendation is to speak with your own Maulavi, or a religious scholar you personally know and trust, before making any decision at all about performing Umrah Badal — both on whether it genuinely applies to your specific family situation, and on exactly how it should be carried out correctly if it does apply. This holds true whether you're considering it for a parent who has passed away, a grandparent, or a relative who is still living but medically unable to travel themselves. Please don't rely on general online explanations, including everything written in this particular article, for the actual religious specifics that will determine what's right and correct for your own situation.",
      "Once you've had that conversation and have genuine clarity on your own family's circumstances, the practical side of actually arranging the trip is something a licensed agency can help with in much the same way as any other Umrah booking, handling flights, visas, and accommodation as they normally would. Our guide on choosing the right agency can help you find an operator experienced with Badal Umrah logistics specifically, including any documentation they may ask for around the arrangement. But the underlying question of whether and how to proceed remains one only your own scholar can properly answer for you — not your travel agent, and certainly not a blog post.",
    ],
    coverImageUrl: BLOG_COVERS.paperPlane,
    category: "Rituals",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-09-12",
    status: "published",
  },
  {
    id: "b25",
    slug: "umrah-during-ramadan-is-extra-cost-worth-it",
    title: "Traveling for Umrah During Ramadan: Is the Extra Cost Worth It?",
    excerpt:
      "What actually changes about performing Umrah in Ramadan — the crowds, the cost, the spiritual pull — and how to weigh it for your own trip.",
    content: [
      "Every year, a good number of Sri Lankan pilgrims deliberately try to time their Umrah for Ramadan, and it isn't hard to understand why. There's a well-known saying attributed to the Prophet Muhammad ﷺ, widely referenced across the Muslim world, that speaks of Umrah performed during Ramadan carrying the reward of Hajj — a tradition that shapes why so many pilgrims feel specifically drawn to travel during this particular month, rather than at any other point in the calendar year. But wanting to travel during Ramadan, and it actually being the right call for your budget, your health, and your family's circumstances, are two genuinely different questions, and it's worth thinking through the real trade-offs honestly before you commit your savings and your limited annual leave to a specific set of dates.",
      "The most obvious difference is the crowds, and it's a bigger difference than most first-time pilgrims tend to expect going in. Masjid al-Haram and Masjid an-Nabawi are busy throughout the year, but during Ramadan — and especially during the last ten nights, when enormous numbers of pilgrims specifically travel in hopes of witnessing Laylatul Qadr — they become dramatically more crowded than at almost any other time on the calendar. Tawaf takes noticeably longer to complete from start to finish, finding space to actually sit or stand for prayer inside the mosque itself becomes far harder the closer you get to those final nights, and simply moving around the wider Haram area on foot takes considerably more time, patience, and physical stamina than it typically would outside of Ramadan.",
      "Cost and availability shift accordingly, and this is exactly where planning ahead matters most for anyone on a fixed budget. Flights, hotels close to the Haram, and full Umrah packages during Ramadan — particularly around the last ten nights — tend to run noticeably higher than they do during quieter months of the year, and good accommodation within easy walking distance of the mosque tends to get booked out well in advance of the month even starting, sometimes months ahead. If Ramadan travel is genuinely what you want, our guide on Umrah cost from Sri Lanka and our Umrah Budget Calculator tool are worth using early in your planning process, since the cost gap compared with other months is real and worth budgeting for properly, even though we won't put a specific figure or percentage on it here without solid, current data to responsibly back it up.",
      "None of this means Ramadan Umrah isn't worth it for the right person, in the right circumstances. For many pilgrims, the atmosphere of taraweeh prayers inside a packed Haram, the shared iftars with pilgrims from dozens of countries all breaking their fast together, and the specific spiritual significance many people personally attach to worship during this month make the extra cost and the physical demands of the crowds feel entirely justified — even a meaningful, memorable part of the experience itself rather than a drawback to tolerate. For others, particularly first-time pilgrims still finding their feet, elderly travellers, or anyone who finds large, dense crowds physically or mentally exhausting rather than energising, a quieter month outside Ramadan can mean more actual time spent close to the Kaaba, noticeably shorter queues, and a calmer, more affordable trip overall.",
      "There's genuinely no universally right answer here — it comes down to your own budget, your and your travel companions' physical stamina for sustained crowds over many days, and whether you're travelling with elderly parents or young children, in which case our guide on group and family packages is worth reading alongside this one before you decide on dates. If you're still undecided, it's worth having a direct, specific conversation with a licensed agency about what Ramadan availability and pricing actually look like for the exact dates you're considering that particular year, rather than making the decision based purely on what you've heard secondhand from someone who travelled in a different season, or even a different Ramadan entirely.",
    ],
    coverImageUrl: BLOG_COVERS.crescentStar,
    category: "Planning",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 8,
    publishedAt: "2026-09-13",
    status: "published",
  },
  {
    id: "b26",
    slug: "umrah-travel-day-documents-checklist",
    title: "The Physical Documents Checklist for Umrah Travel Day",
    excerpt:
      "The exact papers and printouts to have in hand the night before you fly, from passport validity to your vaccination certificate.",
    content: [
      "There's a real difference between understanding Saudi Arabia's visa requirements in general and actually having the right pieces of paper physically in your hand at the airport check-in counter at four in the morning, half-asleep and trying to keep track of family members and luggage at the same time. This checklist is meant for the latter — the night before you fly, when your suitcase is packed, your Ihram is folded on top, and it's finally time to lay out every physical document you'll actually need for travel day itself. It's meant to sit alongside, not replace, our broader guide on Umrah visa requirements, which covers the rules and eligibility side of things rather than the specific paperwork you need sitting in a folder inside your hand luggage.",
      "Start with your passport itself. Check that it has sufficient validity remaining well beyond your travel dates — most airlines and immigration counters expect several months of validity left on a passport before they'll let you board or enter the country, so if yours is getting close to expiry, this is genuinely worth sorting out weeks ahead of time rather than discovering it at the check-in counter on travel day, since exact validity requirements are best confirmed directly with your agency or the relevant authorities closer to your specific travel date. Alongside the original document, carry a couple of photocopies of your passport's information page, kept separately from the original in a different bag or with a different family member, just in case the original is ever lost, damaged, or misplaced somewhere along the way.",
      "Next comes everything tied directly to your visa and your travel arrangements: a printed copy of your visa approval, your flight e-tickets or boarding confirmations, hotel vouchers or booking confirmations for both your Makkah and Madinah stays, and a printed copy of your full return itinerary showing your journey back home. It's tempting, especially for younger or more tech-comfortable travellers, to rely entirely on a phone for all of this, but a dead battery, a lost or stolen phone, or simply no signal at exactly the wrong moment is a real and easily avoidable risk on travel day, so having printed backups of everything genuinely important is well worth the handful of extra pages tucked into your travel folder.",
      "Your vaccination certificate deserves its own specific mention here, separate from the rest of the paperwork. The meningitis (ACYW135) vaccination has long been a well-known entry requirement for pilgrims travelling to Saudi Arabia for both Umrah and Hajj, and you should carry physical proof of having received it alongside your other travel documents, not just a digital record saved somewhere on a health app on your phone. Exact current requirements, timing windows before travel, and any additional vaccines expected of pilgrims can be updated by Saudi health authorities from time to time, so it's worth confirming the specifics that apply to your own travel dates directly with your agency closer to departure — our health and vaccination requirements guide is a solid starting point for this, but should be treated as a starting point rather than the final word for the specific year and season you happen to be travelling in.",
      "Finally, don't overlook the smaller practical extras that are easy to forget entirely in the excitement and stress of last-minute packing: a small amount of cash already converted to Saudi Riyal for immediate needs like a taxi from the airport, a bottle of water, or a snack before you've had a real chance to find a working ATM, and a written list of emergency contacts covering your agency's local representative in Saudi Arabia, a family member back home in Sri Lanka, and the contact details for the Sri Lankan embassy in Saudi Arabia. Our guide on managing money and currency has more detail on getting that particular part right well before you land. The night before you fly, it genuinely helps to lay every one of these items out together in a single folder or travel pouch, so nothing important gets left behind in the rush of an early-morning departure to the airport.",
    ],
    coverImageUrl: BLOG_COVERS.mosque,
    category: "Guides",
    author: "UmrahPackages.lk Editorial",
    readMinutes: 7,
    publishedAt: "2026-09-14",
    status: "published",
  },
];

export const mockMaulavis: Maulavi[] = [
  {
    id: "m1",
    slug: "ustaz-mohamed-rizvi",
    name: "Ustaz Mohamed Rizvi",
    photoUrl: avatar("Rizvi", "0D1B2A"),
    specialization: "Umrah & Hajj Guidance",
    city: "Colombo",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 12,
    phone: "+94 77 111 2233",
    whatsapp: "https://wa.me/94771112233",
  },
  {
    id: "m2",
    slug: "sheikh-abdul-hameed",
    name: "Sheikh Abdul Hameed",
    photoUrl: avatar("Hameed", "C8A24A"),
    specialization: "Fiqh & Pilgrim Counselling",
    city: "Kandy",
    languages: ["Sinhala", "English"],
    yearsExperience: 9,
    phone: "+94 77 222 3344",
    whatsapp: "https://wa.me/94772223344",
  },
  {
    id: "m3",
    slug: "ustaz-fazil-ahamed",
    name: "Ustaz Fazil Ahamed",
    photoUrl: avatar("Fazil", "0D1B2A"),
    specialization: "Ihram Rites & Ziyarah Guidance",
    city: "Kattankudy",
    languages: ["Tamil", "English", "Arabic"],
    yearsExperience: 15,
    phone: "+94 77 333 4455",
    whatsapp: "https://wa.me/94773334455",
  },
  {
    id: "m4",
    slug: "sheikh-nizam-mohideen",
    name: "Sheikh Nizam Mohideen",
    photoUrl: avatar("Nizam", "C8A24A"),
    specialization: "Group Leadership & Pilgrim Counselling",
    city: "Galle",
    languages: ["Sinhala", "Tamil", "English"],
    yearsExperience: 7,
    phone: "+94 77 444 5566",
    whatsapp: "https://wa.me/94774445566",
  },
];

// Inquiries — visible only in the agency/admin dashboards, never on public
// pages. Mix of channels/statuses so the dashboard UI has something to show.
export const mockInquiries: Inquiry[] = [
  {
    id: "i1",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Fathima Rasheed",
    phone: "+94 77 123 4567",
    email: "fathima.r@example.com",
    message: "Is the Nov 12 departure still available for a family of 4?",
    channel: "whatsapp",
    status: "new",
    createdAt: "2026-08-21T09:15:00Z",
  },
  {
    id: "i2",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    packageId: "p1",
    packageTitle: "Premium 14-Day Makkah & Madinah Umrah",
    name: "Mohamed Sadiq",
    phone: "+94 71 987 6543",
    channel: "phone",
    status: "contacted",
    createdAt: "2026-08-19T14:30:00Z",
  },
  {
    id: "i3",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    packageId: "p2",
    packageTitle: "Standard 10-Day Family Umrah Package",
    name: "Aisha Nazeer",
    phone: "+94 76 555 1122",
    email: "aisha.n@example.com",
    message: "Can you split the payment into 3 installments?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T11:05:00Z",
  },
  {
    id: "i4",
    agencyId: "a2",
    agencyName: "Noor Al Haram Tours",
    name: "Ismail Farook",
    phone: "+94 77 222 8899",
    channel: "whatsapp",
    status: "closed",
    createdAt: "2026-08-10T08:00:00Z",
  },
  {
    id: "i5",
    agencyId: "a3",
    agencyName: "Baytullah Travels",
    packageId: "p3",
    packageTitle: "Budget 7-Day Umrah Getaway",
    name: "Zainab Hussain",
    phone: "+94 70 333 4455",
    email: "zainab.h@example.com",
    channel: "email",
    status: "contacted",
    createdAt: "2026-08-15T16:45:00Z",
  },
  {
    id: "i6",
    agencyId: "a1",
    agencyName: "Al-Safa Travels & Tours",
    name: "Riyaz Careem",
    phone: "+94 77 666 7788",
    message: "Do you have a package for a solo traveller in December?",
    channel: "form",
    status: "new",
    createdAt: "2026-08-22T18:20:00Z",
  },
];
